# 01 Importing basic libraries

In [73]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st

# 02. Importing initial data for checking

In [74]:
# Turismo.gov.br - Ministério do Turismo
arrivals_2015 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2015.csv', encoding='latin-1', sep=';')
arrivals_2016 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2016.csv', encoding='latin-1', sep=';')
arrivals_2017 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2017.csv', encoding='latin-1', sep=';')
arrivals_2018 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2018.csv', encoding='latin-1', sep=';')
arrivals_2019 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2019.csv', encoding='latin-1', sep=';')
arrivals_2020 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2020.csv', encoding='latin-1', sep=';')
arrivals_2021 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2021.csv', encoding='latin-1', sep=';')
arrivals_2022 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2022.csv', encoding='latin-1', sep=';')
arrivals_2023 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2023.csv', encoding='latin-1', sep=';') 
arrivals_2024 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2024.csv', encoding='latin-1', sep=';')

In [75]:
# Our World in Data
international_tourism = pd.read_csv('../01. Data/01. Raw Data/Our_World_in_Data/international-tourist-trips.csv')

In [76]:
# UnTourism - UNWTO
international_tourism_un = pd.read_excel('../01. Data/01. Raw Data/UNWTO/02_Inbound/01_Total_arrivals/UN_Tourism_inbound_arrivals_12_2025.xlsx', sheet_name='Data')

# 03.1 Discovery and data understanding - Turismo.gov

In [77]:
arrivals_2015.shape, arrivals_2016.shape, arrivals_2017.shape, arrivals_2018.shape, arrivals_2019.shape, arrivals_2020.shape, arrivals_2021.shape, arrivals_2022.shape, arrivals_2023.shape, arrivals_2024.shape

((46872, 12),
 (44640, 12),
 (43524, 12),
 (46872, 12),
 (49104, 12),
 (47988, 12),
 (55800, 12),
 (54684, 12),
 (34764, 12),
 (22856, 12))

In [78]:
# checking columns names and data structure
arrivals_2015.head()

,Continente,Ordem continente,País,Ordem país,UF,Ordem UF,Via de acesso,Ordem via de acesso,ano,Mês,Ordem mês,Chegadas
0,África,1,África do Sul,2,Acre,1,Terrestre,2,2015,janeiro,1,2
1,África,1,Angola,6,Acre,1,Terrestre,2,2015,janeiro,1,0
2,África,1,Cabo Verde,35,Acre,1,Terrestre,2,2015,janeiro,1,0
3,África,1,Egito,60,Acre,1,Terrestre,2,2015,janeiro,1,0
4,África,1,Gana,77,Acre,1,Terrestre,2,2015,janeiro,1,0

In [79]:
# checking columns names and data structure
arrivals_2016.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Terrestre,2,2016,janeiro,1,1
1,África,1,Angola,6,Acre,1,Terrestre,2,2016,janeiro,1,0
2,África,1,Cabo Verde,35,Acre,1,Terrestre,2,2016,janeiro,1,0
3,África,1,Egito,60,Acre,1,Terrestre,2,2016,janeiro,1,2
4,África,1,Gana,77,Acre,1,Terrestre,2,2016,janeiro,1,0

In [80]:
# checking columns names and data structure
arrivals_2017.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Terrestre,2,2017,janeiro,1,0
1,África,1,Angola,6,Acre,1,Terrestre,2,2017,janeiro,1,0
2,África,1,Cabo Verde,35,Acre,1,Terrestre,2,2017,janeiro,1,0
3,África,1,Egito,60,Acre,1,Terrestre,2,2017,janeiro,1,0
4,África,1,Gana,77,Acre,1,Terrestre,2,2017,janeiro,1,0

In [81]:
# checking columns names and data structure
arrivals_2018.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Fluvial,4,2018,janeiro,1,0
1,África,1,África do Sul,2,Acre,1,Fluvial,4,2018,fevereiro,2,0
2,África,1,África do Sul,2,Acre,1,Fluvial,4,2018,março,3,0
3,África,1,África do Sul,2,Acre,1,Fluvial,4,2018,abril,4,0
4,África,1,África do Sul,2,Acre,1,Fluvial,4,2018,maio,5,0

In [82]:
# checking columns names and data structure
arrivals_2019.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Aérea,1,2019,janeiro,1,0
1,África,1,África do Sul,2,Acre,1,Aérea,1,2019,fevereiro,2,0
2,África,1,África do Sul,2,Acre,1,Aérea,1,2019,março,3,0
3,África,1,África do Sul,2,Acre,1,Aérea,1,2019,abril,4,0
4,África,1,África do Sul,2,Acre,1,Aérea,1,2019,maio,5,0

In [83]:
# checking columns names and data structure
arrivals_2020.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Aérea,1,2020,janeiro,1,0
1,África,1,Angola,6,Acre,1,Aérea,1,2020,janeiro,1,0
2,África,1,Cabo Verde,35,Acre,1,Aérea,1,2020,janeiro,1,0
3,África,1,Egito,60,Acre,1,Aérea,1,2020,janeiro,1,0
4,África,1,Gana,77,Acre,1,Aérea,1,2020,janeiro,1,0

In [84]:
# checking columns names and data structure
arrivals_2021.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Aérea,1,2021,janeiro,1,0
1,África,1,África do Sul,2,Acre,1,Aérea,1,2021,fevereiro,2,0
2,África,1,África do Sul,2,Acre,1,Aérea,1,2021,março,3,0
3,África,1,África do Sul,2,Acre,1,Aérea,1,2021,abril,4,0
4,África,1,África do Sul,2,Acre,1,Aérea,1,2021,maio,5,0

In [85]:
# checking columns names and data structure
arrivals_2022.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Aérea,1,2022,Janeiro,1,0
1,África,1,África do Sul,2,Acre,1,Aérea,1,2022,Fevereiro,2,0
2,África,1,África do Sul,2,Acre,1,Aérea,1,2022,março,3,0
3,África,1,África do Sul,2,Acre,1,Aérea,1,2022,Abril,4,0
4,África,1,África do Sul,2,Acre,1,Aérea,1,2022,Maio,5,0

In [86]:
# checking columns names and data structure
arrivals_2023.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,América do Sul,4,Peru,34,Acre,1,Aéreo,1,2023,Novembro,11,0
1,América do Sul,4,Peru,34,Acre,1,Aéreo,1,2023,Novembro,11,0
2,Ásia,5,Outros países,56,Outras Unidades da Federação,99,Aéreo,1,2023,Junho,6,0
3,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aéreo,1,2023,Janeiro,1,12
4,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aéreo,1,2023,Fevereiro,2,10

In [87]:
# checking columns names and data structure
arrivals_2024.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,10
1,América do Sul,4,Argentina,26,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,1197
2,Europa,6,Bélgica,59,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,3
3,América do Norte,3,Canadá,23,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,2
4,América do Sul,4,Chile,28,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,1

In [90]:
arrivals_2015.isnull().sum(), arrivals_2016.isnull().sum(), arrivals_2017.isnull().sum(), arrivals_2018.isnull().sum(), arrivals_2019.isnull().sum(), arrivals_2020.isnull().sum(), arrivals_2021.isnull().sum(), arrivals_2022.isnull().sum(), arrivals_2023.isnull().sum(), arrivals_2024.isnull().sum()

(Continente             0
 Ordem continente       0
 País                   0
 Ordem país             0
 UF                     0
 Ordem UF               0
 Via de acesso          0
 Ordem via de acesso    0
 ano                    0
 Mês                    0
 Ordem mês              0
 Chegadas               0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64,
 Continente        0
 cod continente    0
 País              0
 cod pais          0
 UF                0
 cod uf            0
 Via               0
 cod via           0
 ano               0
 Mês               0
 cod mes           0
 Chegadas          0
 dtype: int64)

In [91]:
arrivals_2015.dtypes, arrivals_2016.dtypes, arrivals_2017.dtypes, arrivals_2018.dtypes, arrivals_2019.dtypes, arrivals_2020.dtypes, arrivals_2021.dtypes, arrivals_2022.dtypes, arrivals_2023.dtypes, arrivals_2024.dtypes

(Continente               str
 Ordem continente       int64
 País                     str
 Ordem país             int64
 UF                       str
 Ordem UF               int64
 Via de acesso            str
 Ordem via de acesso    int64
 ano                    int64
 Mês                      str
 Ordem mês              int64
 Chegadas               int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object,
 Continente          str
 cod continente    int64
 País                str
 cod pais          int64
 UF                  str
 cod uf            int64
 Via                 str
 cod via           int64
 ano               int64
 Mês                 str
 cod mes           int64
 Chegadas          int64
 dtype: object)

# 03.2 Understanding the Our World in Data and UNWTO

In [92]:
international_tourism.shape, international_tourism_un.shape

((5241, 4), (13900, 13))

In [93]:
# checking columns names - this is already groupped by country and year
international_tourism.head()

    Entity Code  Year  Arrivals of tourists from abroad
0  Albania  ALB  2007                         1062000.0
1  Albania  ALB  2008                         1247000.0
2  Albania  ALB  2009                         1711000.0
3  Albania  ALB  2010                         2191000.0
4  Albania  ALB  2011                         2469000.0

In [94]:
international_tourism.isna().sum()

Entity                               0
Code                                48
Year                                 0
Arrivals of tourists from abroad     0
dtype: int64

In [95]:
international_tourism.dtypes

Entity                                  str
Code                                    str
Year                                  int64
Arrivals of tourists from abroad    float64
dtype: object

In [96]:
# checking the possible raw data from UNWTO - preferential due to more granular data
international_tourism_un.head()

,indicator_code,indicator_label,indicator_previous_code,reporter_area_code,reporter_area_label,partner_area_code,partner_area_label,year,value,flag,flag_label,unit,notes
0,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2000,4.0,NaN,NaN,thousand trips,NaN
1,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2001,4.9,NaN,NaN,thousand trips,NaN
2,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2002,2.8,NaN,NaN,thousand trips,NaN
3,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2003,8.2,NaN,NaN,thousand trips,NaN
4,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2004,3.5,NaN,NaN,thousand trips,NaN

In [97]:
international_tourism_un.isna().sum()

indicator_code                 0
indicator_label                0
indicator_previous_code        0
reporter_area_code             0
reporter_area_label            0
partner_area_code              0
partner_area_label             0
year                           0
value                          0
flag                       13740
flag_label                 13740
unit                           0
notes                      13597
dtype: int64

In [98]:
international_tourism_un.dtypes

indicator_code                 str
indicator_label                str
indicator_previous_code        str
reporter_area_code           int64
reporter_area_label            str
partner_area_code            int64
partner_area_label             str
year                         int64
value                      float64
flag                           str
flag_label                     str
unit                           str
notes                          str
dtype: object