# 01. Importing basic libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st

In [2]:
import sys
sys.path.append('..')

from src.functions import *

# 02. Importing data

In [3]:
# Turismo.gov.br - Ministério do Turismo
arrivals_2015 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2015.csv', encoding='latin-1', sep=';')
arrivals_2016 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2016.csv', encoding='latin-1', sep=';')
arrivals_2017 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2017.csv', encoding='latin-1', sep=';')
arrivals_2018 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2018.csv', encoding='latin-1', sep=';')
arrivals_2019 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2019.csv', encoding='latin-1', sep=';')
arrivals_2020 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2020.csv', encoding='latin-1', sep=';')
arrivals_2021 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2021.csv', encoding='latin-1', sep=';')
arrivals_2022 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2022.csv', encoding='latin-1', sep=';')
arrivals_2023 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2023.csv', encoding='latin-1', sep=';') 
arrivals_2024 = pd.read_csv('../01. Data/01. Raw Data/Turismo.gov/chegadas_2024.csv', encoding='latin-1', sep=';')

In [4]:
# UnTourism - UNWTO
unwto = pd.read_excel('../01. Data/01. Raw Data/UNWTO/02_Inbound/01_Total_arrivals/UN_Tourism_inbound_arrivals_12_2025.xlsx', sheet_name='Data')

# 03.1 Cleaning and wrangling of turismo.gov

### Cleaning

In [5]:
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.shape)

(46872, 12)
(44640, 12)
(43524, 12)
(46872, 12)
(49104, 12)
(47988, 12)
(55800, 12)
(54684, 12)
(34764, 12)
(22856, 12)

In [6]:
# checking columns names to create dictionary for standardization
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.columns)

Index(['Continente', 'Ordem continente', 'País', 'Ordem país', 'UF',
       'Ordem UF', 'Via de acesso', 'Ordem via de acesso', 'ano', 'Mês',
       'Ordem mês', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')
Index(['Continente', 'cod continente', 'País', 'cod pais', 'UF', 'cod uf',
       'Via', 'cod via', 'ano', 'Mês', 'cod mes', 'Chegadas'],
      dtype='str')

In [7]:
# standardize column names - dictionary for renaming columns
columns_mapping = {'Continente' : 'continent', 'Ordem continente' : 'continent_code', 'cod continente' : 'continent_code', 'País' : 'country_of_origin', 'Ordem país' : 'country_code', 'cod pais' : 'country_code', 'UF' : 'state', 'cod uf' : 'state_code', 
                   'Ordem UF' : 'state_code', 'Via de acesso' : 'entry_route', 'Via' : 'entry_route', 'Ordem via de acesso' : 'entry_route_code', 'cod via' : 'entry_route_code', 'ano' : 'year', 'Mês' : 'month', 
                   'Ordem mês' : 'month_code', 'cod mes' : 'month_code', 'Chegadas' : 'arrivals'}

In [8]:
# standardize column names - calling function to rename columns
arrivals_2015 = standardize_columns(arrivals_2015, columns_mapping)
arrivals_2016 = standardize_columns(arrivals_2016, columns_mapping) 
arrivals_2017 = standardize_columns(arrivals_2017, columns_mapping)
arrivals_2018 = standardize_columns(arrivals_2018, columns_mapping)
arrivals_2019 = standardize_columns(arrivals_2019, columns_mapping)
arrivals_2020 = standardize_columns(arrivals_2020, columns_mapping)
arrivals_2021 = standardize_columns(arrivals_2021, columns_mapping)
arrivals_2022 = standardize_columns(arrivals_2022, columns_mapping)
arrivals_2023 = standardize_columns(arrivals_2023, columns_mapping)
arrivals_2024 = standardize_columns(arrivals_2024, columns_mapping)

In [9]:
# checking if the column names are the same across all datasets
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.columns)

Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')
Index(['continent', 'continent_code', 'country_of_origin', 'country_code',
       'state', 'state_code', 'entry_route', 'entry_route_code', 'year',
       'month', 'month_code', 'arrivals'],
      dtype='str')

In [10]:
# checking for null values in each dataset
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
dfs = [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, 
       arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]

for df, year in zip(dfs, years):
    print(f"=== {year} ===")
    print(df.isnull().sum())

=== 2015 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2016 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2017 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2018 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2019 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2020 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2021 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2022 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2023 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64
=== 2024 ===
continent            0
continent_code       0
country_of_origin    0
country_code         0
state                0
state_code           0
entry_route          0
entry_route_code     0
year                 0
month                0
month_code           0
arrivals             0
dtype: int64

In [11]:
# checking for duplicates in each dataset
for df, year in zip(dfs, years):
    print(f"=== {year} ===")
    print(df.duplicated().sum())

=== 2015 ===
0
=== 2016 ===
0
=== 2017 ===
0
=== 2018 ===
0
=== 2019 ===
0
=== 2020 ===
0
=== 2021 ===
0
=== 2022 ===
0
=== 2023 ===
6026
=== 2024 ===
1640

In [12]:
# dropping columns - dictionary for dropping columns
columns_to_drop = ['continent_code', 'country_code', 'state_code', 'entry_route_code', 'month_code']

In [13]:
# dropping columns - calling function to drop columns
arrivals_2015 = dropping_columns(arrivals_2015, columns_to_drop)
arrivals_2016 = dropping_columns(arrivals_2016, columns_to_drop) 
arrivals_2017 = dropping_columns(arrivals_2017, columns_to_drop)
arrivals_2018 = dropping_columns(arrivals_2018, columns_to_drop)
arrivals_2019 = dropping_columns(arrivals_2019, columns_to_drop)
arrivals_2020 = dropping_columns(arrivals_2020, columns_to_drop)
arrivals_2021 = dropping_columns(arrivals_2021, columns_to_drop)
arrivals_2022 = dropping_columns(arrivals_2022, columns_to_drop)
arrivals_2023 = dropping_columns(arrivals_2023, columns_to_drop)
arrivals_2024 = dropping_columns(arrivals_2024, columns_to_drop)

In [14]:
# dropping columns - checking if the column are the same in all data sets
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.columns)

Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')
Index(['continent', 'country_of_origin', 'state', 'entry_route', 'year',
       'month', 'arrivals'],
      dtype='str')

In [15]:
# checking the shape of the datasets after dropping columns
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.shape)

(46872, 7)
(44640, 7)
(43524, 7)
(46872, 7)
(49104, 7)
(47988, 7)
(55800, 7)
(54684, 7)
(34764, 7)
(22856, 7)

In [16]:
# checking data types of the columns in each dataset before concatenation
for df in [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]:
    print(df.dtypes)

continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object
continent              str
country_of_origin      str
state                  str
entry_route            str
year                 int64
month                  str
arrivals             int64
dtype: object

In [17]:
# concatenating datasets into one dataframe
dfs_reduced = [arrivals_2015, arrivals_2016, arrivals_2017, arrivals_2018, arrivals_2019, 
       arrivals_2020, arrivals_2021, arrivals_2022, arrivals_2023, arrivals_2024]

arrivals_10y = concat_dfs(dfs_reduced)

In [18]:
# fixing casing and trimming whitespace in string columns - calling function to format string columns
arrivals_10y = string_formatting(arrivals_10y)

In [19]:
# checking for values counts in each column of the concatenated dataframe
value_counts_by_column(arrivals_10y)

=== continent ===
continent
europa                         161631
ásia                            88129
américa do sul                  60702
américa central e caribe        51595
áfrica                          51162
américa do norte                15548
oceania                         14054
continente não especificado      4283
Name: count, dtype: int64

=== country_of_origin ===
country_of_origin
outros países                                26381
argentina                                     5707
frança                                        5424
alemanha                                      5422
estados unidos                                5405
                                             ...
outros países da áfrica                       1051
outros países da ásia                          884
outros países da europa                        832
outros países da américa central e caribe      515
outros países da oceania                        63
Name: count, Length: 94, dtype: int64

=== state ===
state
rio grande do sul               43040
paraná                          36560
santa catarina                  35195
outras unidades da federação    30799
mato grosso do sul              28762
amapá                           28657
são paulo                       25877
pará                            24024
amazonas                        23840
rio de janeiro                  23345
roraima                         22874
acre                            21335
bahia                           20759
pernambuco                      20595
ceará                           20250
rio grande do norte             19092
distrito federal                11387
minas gerais                    10713
Name: count, dtype: int64

=== entry_route ===
entry_route
aérea        168180
terrestre     99435
marítima      95918
fluvial       61202
aéreo         18880
marítimo       3489
Name: count, dtype: int64

=== year ===
year
2021    55800
2022    54684
2019    49104
2020    47988
2015    46872
2018    46872
2016    44640
2017    43524
2023    34764
2024    22856
Name: count, dtype: int64

=== month ===
month
dezembro     39528
novembro     39190
outubro      38624
abril        36968
janeiro      36817
fevereiro    36795
setembro     36575
julho        36515
agosto       36508
maio         36433
junho        36368
março        34658
marco         2125
Name: count, dtype: int64

=== arrivals ===
arrivals
0        302055
1         29577
2         16392
3         10082
4          7153
          ...
52899         1
11171         1
5171          1
9771          1
4408          1
Name: count, Length: 5454, dtype: int64

In [20]:
# checking for duplicates in the concatenated dataframe
print(arrivals_10y.duplicated().sum())

7666

In [21]:
# dropping duplicates in the concatenated dataframe
arrivals_10y = arrivals_10y.drop_duplicates()

In [22]:
# checking if duplicates were dropped
print(arrivals_10y.duplicated().sum())

0

### Wrangling

In [23]:
# creating dictionaries for translating categorical variables into English
continent_translation = {'américa do sul' : 'south america', 'américa do norte' : 'north america', 'europa' : 'europe', 'ásia' : 'asia', 'áfrica' : 'africa', 'oceania' : 'oceania', 
                     'continente não especificado' : 'unspecified continent', 'américa central e caribe' : 'central america and caribbean'}

entry_route_translation = {'aérea' : 'air', 'aéreo' : 'air', 'marítima' : 'sea', 'marítimo' : 'sea', 'fluvial' : 'river', 'terrestre' : 'land'}

months_translation = {'janeiro' : 'january', 'fevereiro' : 'february', 'março' : 'march', 'marco' : 'march', 'abril' : 'april', 'maio' : 'may', 'junho' : 'june', 'julho' : 'july', 'agosto' : 'august', 'setembro' : 'september', 
                  'outubro' : 'october', 'novembro' : 'november',  'dezembro' : 'december'}

country_of_origin_translation = {
    'alemanha': 'germany',
    'angola': 'angola',
    'argentina': 'argentina',
    'arábia saudita': 'saudi arabia',
    'austrália': 'australia',
    'bangladesh': 'bangladesh',
    'bolívia': 'bolivia',
    'bulgária': 'bulgaria',
    'bélgica': 'belgium',
    'cabo verde': 'cabo verde',
    'canadá': 'canada',
    'chile': 'chile',
    'china': 'china',
    'china, hong kong': 'china, hong kong',
    'cingapura': 'singapore',
    'colômbia': 'colombia',
    'costa rica': 'costa rica',
    'croácia': 'croatia',
    'cuba': 'cuba',
    'dinamarca': 'denmark',
    'egito': 'egypt',
    'el salvador': 'el salvador',
    'equador': 'ecuador',
    'eslováquia': 'slovakia',
    'eslovênia': 'slovenia',
    'espanha': 'spain',
    'estados unidos': 'united states',
    'estônia': 'estonia',
    'filipinas': 'philippines',
    'finlândia': 'finland',
    'frança': 'france',
    'gana': 'ghana',
    'grécia': 'greece',
    'guatemala': 'guatemala',
    'guiana': 'guyana',
    'guiana francesa': 'french guiana',
    'haiti': 'haiti',
    'holanda': 'netherlands',
    'honduras': 'honduras',
    'hungria': 'hungary',
    'indonésia': 'indonesia',
    'irlanda': 'ireland',
    'irã': 'iran',
    'israel': 'israel',
    'itália': 'italy',
    'japão': 'japan',
    'letônia': 'latvia',
    'lituânia': 'lithuania',
    'luxemburgo': 'luxembourg',
    'líbano': 'lebanon',
    'malásia': 'malaysia',
    'marrocos': 'morocco',
    'moçambique': 'mozambique',
    'méxico': 'mexico',
    'nicarágua': 'nicaragua',
    'nigéria': 'nigeria',
    'noruega': 'norway',
    'nova zelândia': 'new zealand',
    'outros países': 'others',
    'outros países da américa central e caribe': 'others from central america and caribbean',
    'outros países da europa': 'others from europe',
    'outros países da oceania': 'others from oceania',
    'outros países da áfrica': 'others from africa',
    'outros países da ásia': 'others from asia',
    'panamá': 'panama',
    'paquistão': 'pakistan',
    'paraguai': 'paraguay',
    'países não especificados': 'unspecified',
    'peru': 'peru',
    'polônia': 'poland',
    'portugal': 'portugal',
    'quênia': 'kenya',
    'reino unido': 'united kingdom',
    'república dominicana': 'dominican republic',
    'república tcheca': 'czechia',
    'república da coreia': 'south korea',
    'romênia': 'romania',
    'rússia': 'russia',
    'suriname': 'suriname',
    'suécia': 'sweden',
    'suíça': 'switzerland',
    'sérvia': 'serbia',
    'síria': 'syria',
    'tailândia': 'thailand',
    'taiwan': 'taiwan',
    'trinidad e tobago': 'trinidad and tobago',
    'tunísia': 'tunisia',
    'turquia': 'turkey',
    'ucrânia': 'ukraine',
    'uruguai': 'uruguay',
    'venezuela': 'venezuela',
    'áfrica do sul': 'south africa',
    'áustria': 'austria',
    'índia': 'india'
}

In [24]:
# calling function to translate categorical variables into English
arrivals_10y = translate_values(arrivals_10y, 'continent', continent_translation)
arrivals_10y = translate_values(arrivals_10y, 'entry_route', entry_route_translation)
arrivals_10y = translate_values(arrivals_10y, 'month', months_translation)
arrivals_10y = translate_values(arrivals_10y, 'country_of_origin', country_of_origin_translation)

In [25]:
# checking values in each column of the concatenated dataframe - checking if translation was successful
value_counts_by_column(arrivals_10y)

=== continent ===
continent
europe                           159153
asia                              86703
south america                     59818
central america and caribbean     50764
africa                            49532
north america                     15283
oceania                           13908
unspecified continent              4277
Name: count, dtype: int64

=== country_of_origin ===
country_of_origin
others                                       23517
argentina                                     5606
france                                        5312
germany                                       5310
united states                                 5294
                                             ...
others from asia                               608
others from africa                             573
others from europe                             563
others from central america and caribbean      374
others from oceania                             48
Name: count, Length: 94, dtype: int64

=== state ===
state
rio grande do sul               41560
paraná                          35526
santa catarina                  35096
outras unidades da federação    30657
mato grosso do sul              28559
amapá                           28503
são paulo                       24289
pará                            23940
amazonas                        23756
roraima                         22677
rio de janeiro                  22203
acre                            21190
bahia                           20416
pernambuco                      20328
ceará                           19986
rio grande do norte             19053
distrito federal                11077
minas gerais                    10622
Name: count, dtype: int64

=== entry_route ===
entry_route
air      182943
sea       98880
land      96646
river     60969
Name: count, dtype: int64

=== year ===
year
2021    55800
2022    54684
2019    49104
2020    47988
2015    46872
2018    46872
2016    44640
2017    43524
2023    28738
2024    21216
Name: count, dtype: int64

=== month ===
month
december     38249
november     37587
october      37184
april        36574
march        36499
january      36494
february     36473
september    36126
august       36122
july         36112
may          36043
june         35975
Name: count, dtype: int64

=== arrivals ===
arrivals
0        297509
1         27754
2         15871
3          9883
4          7019
          ...
52899         1
11171         1
5171          1
9771          1
4408          1
Name: count, Length: 5454, dtype: int64

In [26]:
# checking if "unespecified continent" has any country of origin associated with it
arrivals_10y[arrivals_10y['continent'] == 'unspecified continent']['country_of_origin'].unique()

<ArrowStringArray>
['unspecified']
Length: 1, dtype: str

In [27]:
# creating labels for pre, during and post pandemic periods
arrivals_10y = add_covid_flag(arrivals_10y)

In [28]:
# checking if labels were crated correctly
arrivals_10y.value_counts('covid_period')

covid_period
pre_covid     231012
post_covid    104638
covid         103788
Name: count, dtype: int64

In [29]:
# checking if the labels are correctly input by sampling some rows
arrivals_10y[['year', 'covid_period']].sample(20)

        year covid_period
310466  2021        covid
431059  2024   post_covid
80216   2016    pre_covid
56255   2016    pre_covid
438459  2024   post_covid
222301  2019    pre_covid
99735   2017    pre_covid
373492  2022   post_covid
307872  2021        covid
99204   2017    pre_covid
325065  2021        covid
108571  2017    pre_covid
87788   2016    pre_covid
218967  2019    pre_covid
330608  2021        covid
300860  2021        covid
59387   2016    pre_covid
155180  2018    pre_covid
437195  2024   post_covid
323814  2021        covid

In [30]:
# creating new column for seasons
arrivals_10y = seasons_brazil(arrivals_10y, 'month')

In [31]:
arrivals_10y['season'].value_counts()

season
summer    111216
spring    110897
autumn    109116
winter    108209
Name: count, dtype: int64

# 03.2 Cleaning and wrangling of UNTWO data

### Cleaning

In [32]:
unwto.head()

,indicator_code,indicator_label,indicator_previous_code,reporter_area_code,reporter_area_label,partner_area_code,partner_area_label,year,value,flag,flag_label,unit,notes
0,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2000,4.0,NaN,NaN,thousand trips,NaN
1,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2001,4.9,NaN,NaN,thousand trips,NaN
2,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2002,2.8,NaN,NaN,thousand trips,NaN
3,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2003,8.2,NaN,NaN,thousand trips,NaN
4,INBD_TRIP_TOTL_CRUS_EXCR,inbound - trips - total - cruise ships - same-...,CP_1_4,16,American Samoa,999,World,2004,3.5,NaN,NaN,thousand trips,NaN

In [33]:
unwto.shape

(13900, 13)

In [34]:
# standardize column names - dictionary for renaming columns
unwto_columns_mapping = {'reporter_area_code' : 'country_code', 'reporter_area_label' : 'country_name', 'value' : 'arrivals', 'indicator_label' : 'type_of_arrival'}

In [35]:
# standardize column names - calling function to rename columns
unwto = standardize_columns(unwto, unwto_columns_mapping)

In [36]:
# standardize column names - checking the renaming of columns
unwto.columns

Index(['indicator_code', 'type_of_arrival', 'indicator_previous_code',
       'country_code', 'country_name', 'partner_area_code',
       'partner_area_label', 'year', 'arrivals', 'flag', 'flag_label', 'unit',
       'notes'],
      dtype='str')

In [37]:
# handling null values - checking for null values in the dataset
unwto.isnull().sum()

indicator_code                 0
type_of_arrival                0
indicator_previous_code        0
country_code                   0
country_name                   0
partner_area_code              0
partner_area_label             0
year                           0
arrivals                       0
flag                       13740
flag_label                 13740
unit                           0
notes                      13597
dtype: int64

In [38]:
# checking for duplicates dataset
unwto.duplicated().sum()

np.int64(0)

In [39]:
# checking values in each column of the concatenated dataframe
value_counts_by_column(unwto)

=== indicator_code ===
indicator_code
INBD_TRIP_TOTL_TOTL_TOUR    5241
INBD_TRIP_TOTL_TOTL_VSTR    3794
INBD_TRIP_TOTL_TOTL_EXCR    2985
INBD_TRIP_TOTL_CRUS_EXCR    1880
Name: count, dtype: int64

=== type_of_arrival ===
type_of_arrival
inbound - trips - total - total - overnight visitors (tourists)               5241
inbound - trips - total - total - visitors                                    3794
inbound - trips - total - total - same-day visitors (excursionists)           2985
inbound - trips - total - cruise ships - same-day visitors (excursionists)    1880
Name: count, dtype: int64

=== indicator_previous_code ===
indicator_previous_code
CP_1_2    5241
CP_1_1    3794
CP_1_3    2985
CP_1_4    1880
Name: count, dtype: int64

=== country_code ===
country_code
44     118
188    118
214    118
484    118
400    117
      ...
624     16
626     16
368     13
703      7
478      2
Name: count, Length: 215, dtype: int64

=== country_name ===
country_name
Bahamas               118
Costa Rica            118
Dominican Republic    118
Mexico                118
Jordan                117
                     ...
Guinea-Bissau          16
Timor-Leste            16
Iraq                   13
Slovakia                7
Mauritania              2
Name: count, Length: 215, dtype: int64

=== partner_area_code ===
partner_area_code
999    13900
Name: count, dtype: int64

=== partner_area_label ===
partner_area_label
World    13900
Name: count, dtype: int64

=== year ===
year
2017    512
2016    511
2015    507
2010    506
2008    505
2011    502
2007    502
2006    499
2009    498
2013    497
2001    496
2005    495
2012    495
2014    492
2020    491
2000    487
2018    487
2019    485
2003    484
2004    483
2002    479
1999    479
1998    472
1996    458
1997    458
1995    445
2021    429
2022    384
2023    183
2024    179
Name: count, dtype: int64

=== arrivals ===
arrivals
9.0       60
2.0       50
6.0       48
4.0       47
7.0       45
          ..
1175.0     1
1282.0     1
21.5       1
24.9       1
23.7       1
Name: count, Length: 6051, dtype: int64

=== flag ===
flag
D    141
E     16
B      2
P      1
Name: count, dtype: int64

=== flag_label ===
flag_label
Definition differs    141
Estimated value        16
Time series break       2
Provisional value       1
Name: count, dtype: int64

=== unit ===
unit
thousand trips    13900
Name: count, dtype: int64

=== notes ===
notes
Value represents overnight visitors (tourists) only. No data available for same-day visitors (excursionists)                                                     141
total from trips by main purpose.                                                                                                                                 15
Fuente: Subsecretaría de Turismo de la Nación en base a INDEC.                                                                                                    10
Source: Borders data & Inbound Visitor Survey.                                                                                                                    10
Tourist and excursionist trips estimated based on official migration records.                                                                                     10
Since October 2024 the “Place of residence” data derived solely from arrival cards is no longer available and all reports would be based on Nationality data.     10
Personal, business and work-relates tourism together.                                                                                                             10
Excluding Arrivals of Non-Residents Indians (NRIs).                                                                                                               10
Source: Borders Data, Inbound Visitor Survey.                                                                                                                     10
Source: International Passenger Survey.                                                                                                                           10
Source: database of information system of the border electronic control of RA of National Security Service of RA  .                                                5
Data from the Border Survey on 'Vols Extérieurs' ; no daily data.                                                                                                  5
Supply-side.                                                                                                                                                       5
supply-side data.                                                                                                                                                  5
source: TOURSTAT.                                                                                                                                                  5
Number of arrivals in market accommodation.                                                                                                                        5
Source: Statistics Portugal (INE PT) - Estimates of International Tourism.                                                                                         5
Source: International travels registered at the Romanian Borders.                                                                                                  5
Source: supply-side survey (accommodation statistics).                                                                                                             5
Data from: https://www.trade.gov/i-94-arrivals-program.                                                                                                            5
 Fuente: MINCIT - Colombia.                                                                                                                                        5
 Source: Kenya National Bureau of Statistics (KNBS).                                                                                                               5
Total number of visitors according to hotel system.                                                                                                                4
total from trips by mode of transport.                                                                                                                             3
Name: count, dtype: int64

In [40]:
# dropping columns - dictionary for dropping columns
unwto_columns_to_drop = ['notes', 'unit', 'flag_label','flag', 'partner_area_label', 'partner_area_code', 'country_code', 'indicator_previous_code', 'indicator_code']

In [41]:
# calling function to drop columns
unwto = dropping_columns(unwto, unwto_columns_to_drop)

In [42]:
# checking if the column were dropped correctly
unwto.columns

Index(['type_of_arrival', 'country_name', 'year', 'arrivals'], dtype='str')

In [43]:
# checking dtypes of the columns in the dataset
unwto.dtypes

type_of_arrival        str
country_name           str
year                 int64
arrivals           float64
dtype: object

In [44]:
# fixing casing and trimming whitespace in string columns - calling function to format string columns
unwto = string_formatting(unwto)

In [45]:
# dropping rows with data before 2015 and after 2024, as we want to align the UNWTO dataset with the turismo.gov dataset
unwto = unwto[(unwto['year'] >= 2015) & (unwto['year'] <= 2024)]

In [46]:
# checking if dropping worked by checking the head
unwto.head()

,type_of_arrival,country_name,year,arrivals
11,inbound - trips - total - cruise ships - same-...,american samoa,2015,26.8
12,inbound - trips - total - cruise ships - same-...,american samoa,2016,18.2
13,inbound - trips - total - cruise ships - same-...,american samoa,2017,22.3
14,inbound - trips - total - cruise ships - same-...,american samoa,2018,31.6
15,inbound - trips - total - cruise ships - same-...,american samoa,2019,39.4

In [47]:
# for column type_of_arrival, analyse if the labels are subset of each other
years = [2018, 2019]

unwto[(unwto['country_name'] == 'american samoa') & (unwto['year'].isin(years))].sort_values('year')

,type_of_arrival,country_name,year,arrivals
14,inbound - trips - total - cruise ships - same-...,american samoa,2018,31.6
1918,inbound - trips - total - total - overnight vi...,american samoa,2018,20.2
10174,inbound - trips - total - total - visitors,american samoa,2018,51.8
7147,inbound - trips - total - total - same-day vis...,american samoa,2018,31.6
1919,inbound - trips - total - total - overnight vi...,american samoa,2019,19.2
15,inbound - trips - total - cruise ships - same-...,american samoa,2019,39.4
7148,inbound - trips - total - total - same-day vis...,american samoa,2019,39.4
10175,inbound - trips - total - total - visitors,american samoa,2019,58.6

In [48]:
# for column type_of_arrival, analyse if the labels are subset of each other
years = [2018, 2019]

unwto[(unwto['country_name'] == 'greece') & (unwto['year'].isin(years))].sort_values('year')

,type_of_arrival,country_name,year,arrivals
551,inbound - trips - total - cruise ships - same-...,greece,2018,2949.0
3721,inbound - trips - total - total - overnight vi...,greece,2018,30123.0
11355,inbound - trips - total - total - visitors,greece,2018,33072.0
7993,inbound - trips - total - total - same-day vis...,greece,2018,2949.0
3722,inbound - trips - total - total - overnight vi...,greece,2019,31348.4
552,inbound - trips - total - cruise ships - same-...,greece,2019,2656.2
7994,inbound - trips - total - total - same-day vis...,greece,2019,2656.2
11356,inbound - trips - total - total - visitors,greece,2019,34005.0

In [49]:
# for column type_of_arrival, analyse if the labels are subset of each other
years = [2018, 2019]

unwto[(unwto['country_name'] == 'dominican republic') & (unwto['year'].isin(years))].sort_values('year')

,type_of_arrival,country_name,year,arrivals
446,inbound - trips - total - cruise ships - same-...,dominican republic,2018,982.0
3286,inbound - trips - total - total - overnight vi...,dominican republic,2018,6569.0
11050,inbound - trips - total - total - visitors,dominican republic,2018,7551.0
7774,inbound - trips - total - total - same-day vis...,dominican republic,2018,982.0
3287,inbound - trips - total - total - overnight vi...,dominican republic,2019,6446.0
447,inbound - trips - total - cruise ships - same-...,dominican republic,2019,1104.0
7775,inbound - trips - total - total - same-day vis...,dominican republic,2019,1104.0
11051,inbound - trips - total - total - visitors,dominican republic,2019,7550.0

In [50]:
# dropping rows with inbound - trips - total - total - visitors and inbound - trips - total - cruise ships - same-day visitors (excursionists) as they are subsets of other categories
unwto = unwto[~unwto['type_of_arrival'].isin(['inbound - trips - total - total - visitors', 'inbound - trips - total - cruise ships - same-day visitors (excursionists)'])]

In [51]:
# checking if dropping worked by checking value counts in the columntype_of_arrival
value_counts_by_column(unwto)

=== type_of_arrival ===
type_of_arrival
inbound - trips - total - total - overnight visitors (tourists)        1518
inbound - trips - total - total - same-day visitors (excursionists)     897
Name: count, dtype: int64

=== country_name ===
country_name
albania                       20
andorra                       20
bahamas                       20
bahrain                       20
canada                        20
                              ..
qatar                          3
iran (islamic republic of)     2
viet nam                       2
yemen                          2
russian federation             1
Name: count, Length: 196, dtype: int64

=== year ===
year
2015    300
2016    298
2017    297
2018    284
2019    283
2020    279
2021    248
2022    215
2023    107
2024    104
Name: count, dtype: int64

=== arrivals ===
arrivals
82.0     7
55.0     7
2.0      7
218.0    6
255.0    6
        ..
558.5    1
387.6    1
545.0    1
8.6      1
31.8     1
Name: count, Length: 1926, dtype: int64

### Wrangling

In [52]:
# Standardize/translating column values — Checking column values to evaluate needs
value_counts_by_column(unwto)

=== type_of_arrival ===
type_of_arrival
inbound - trips - total - total - overnight visitors (tourists)        1518
inbound - trips - total - total - same-day visitors (excursionists)     897
Name: count, dtype: int64

=== country_name ===
country_name
albania                       20
andorra                       20
bahamas                       20
bahrain                       20
canada                        20
                              ..
qatar                          3
iran (islamic republic of)     2
viet nam                       2
yemen                          2
russian federation             1
Name: count, Length: 196, dtype: int64

=== year ===
year
2015    300
2016    298
2017    297
2018    284
2019    283
2020    279
2021    248
2022    215
2023    107
2024    104
Name: count, dtype: int64

=== arrivals ===
arrivals
82.0     7
55.0     7
2.0      7
218.0    6
255.0    6
        ..
558.5    1
387.6    1
545.0    1
8.6      1
31.8     1
Name: count, Length: 1926, dtype: int64

In [53]:
# creating dictionary for column type_of_arrival
type_of_arrival_translation = {'inbound - trips - total - total - overnight visitors (tourists)' : 'overnight tourist', 'inbound - trips - total - total - same-day visitors (excursionists)' : 'same-day visitor'}

In [54]:
# calling function for column type_of_arrival
unwto = translate_values(unwto, 'type_of_arrival', type_of_arrival_translation)

In [55]:
# checking if standarization worked by checking value counts in the column
value_counts_by_column(unwto)

=== type_of_arrival ===
type_of_arrival
overnight tourist    1518
same-day visitor      897
Name: count, dtype: int64

=== country_name ===
country_name
albania                       20
andorra                       20
bahamas                       20
bahrain                       20
canada                        20
                              ..
qatar                          3
iran (islamic republic of)     2
viet nam                       2
yemen                          2
russian federation             1
Name: count, Length: 196, dtype: int64

=== year ===
year
2015    300
2016    298
2017    297
2018    284
2019    283
2020    279
2021    248
2022    215
2023    107
2024    104
Name: count, dtype: int64

=== arrivals ===
arrivals
82.0     7
55.0     7
2.0      7
218.0    6
255.0    6
        ..
558.5    1
387.6    1
545.0    1
8.6      1
31.8     1
Name: count, Length: 1926, dtype: int64

In [56]:
# Convert arrivals column to full numbers (multiply by 1000, as per old column units)
unwto['arrivals'] = (unwto['arrivals'] * 1000).astype(int)

In [57]:
# checking if convertion worked correctly by checking the head of the dataset
unwto.head()

        type_of_arrival country_name  year  arrivals
1888  overnight tourist      albania  2015   3784000
1889  overnight tourist      albania  2016   4070000
1890  overnight tourist      albania  2017   4643000
1891  overnight tourist      albania  2018   5340000
1892  overnight tourist      albania  2019   6128000

In [58]:
# creating labels for pre, during and post pandemic periods
unwto = add_covid_flag(unwto)

In [59]:
# checking if the labels are correctly input by sampling some rows
unwto[['year', 'covid_period']].sample(20)

       year covid_period
2118   2021        covid
7859   2019    pre_covid
10024  2015    pre_covid
3867   2018    pre_covid
4048   2021        covid
4436   2020        covid
9554   2023   post_covid
8311   2020        covid
9729   2016    pre_covid
8170   2022   post_covid
6795   2019    pre_covid
2521   2015    pre_covid
7263   2022   post_covid
2054   2024   post_covid
6588   2022   post_covid
9830   2017    pre_covid
9947   2019    pre_covid
5055   2021        covid
6650   2016    pre_covid
6040   2021        covid

In [60]:
# standardizing country names in the column country_name to create continent column aligned with turismo.gov dataset
unwto_country_corrections = {
    'bolivia (plurinational state of)': 'bolivia',
    'china, hong kong special administrative region': 'china, hong kong',
    'united states of america': 'united states',
    'netherlands (kingdom of the)': 'netherlands',
    'iran (islamic republic of)': 'iran',
    'united kingdom of great britain and northern ireland': 'united kingdom',
    'russian federation': 'russia',
    'syrian arab republic': 'syria',
    'taiwan province of china': 'taiwan',
    'venezuela (bolivarian republic of)': 'venezuela',
    'türkiye': 'turkey',
    'republic of korea': 'south korea',
    'micronesia (federated states of)': 'micronesia',
    'viet nam': 'vietnam',
    'sint maarten (dutch part)': 'saint maarten (dutch part)',
}

In [61]:
# calling the function to standardize country names in the column country_name
unwto = translate_values(unwto, 'country_name', unwto_country_corrections)

In [62]:
# creating dictionary for creation of continent column
continent_mapping = {
    # africa
    'algeria': 'africa',
    'angola': 'africa',
    'benin': 'africa',
    'botswana': 'africa',
    'burkina faso': 'africa',
    'burundi': 'africa',
    'cabo verde': 'africa',
    'cameroon': 'africa',
    'central african republic': 'africa',
    'chad': 'africa',
    'comoros': 'africa',
    'congo': 'africa',
    "côte d'ivoire": 'africa',
    'democratic republic of the congo': 'africa',
    'djibouti': 'africa',
    'egypt': 'africa',
    'eritrea': 'africa',
    'eswatini': 'africa',
    'ethiopia': 'africa',
    'gabon': 'africa',
    'gambia': 'africa',
    'ghana': 'africa',
    'guinea': 'africa',
    'guinea-bissau': 'africa',
    'kenya': 'africa',
    'lesotho': 'africa',
    'libya': 'africa',
    'madagascar': 'africa',
    'malawi': 'africa',
    'mali': 'africa',
    'mauritania': 'africa',
    'mauritius': 'africa',
    'morocco': 'africa',
    'mozambique': 'africa',
    'namibia': 'africa',
    'niger': 'africa',
    'nigeria': 'africa',
    'rwanda': 'africa',
    'réunion': 'africa',
    'sao tome and principe': 'africa',
    'senegal': 'africa',
    'seychelles': 'africa',
    'sierra leone': 'africa',
    'south africa': 'africa',
    'sudan': 'africa',
    'togo': 'africa',
    'tunisia': 'africa',
    'uganda': 'africa',
    'united republic of tanzania': 'africa',
    'zambia': 'africa',
    'zimbabwe': 'africa',

    # asia
    'armenia': 'asia',
    'azerbaijan': 'asia',
    'bahrain': 'asia',
    'bangladesh': 'asia',
    'bhutan': 'asia',
    'brunei darussalam': 'asia',
    'cambodia': 'asia',
    'china': 'asia',
    'china, hong kong': 'asia',
    'china, macao special administrative region': 'asia',
    'georgia': 'asia',
    'india': 'asia',
    'indonesia': 'asia',
    'iran': 'asia',
    'iraq': 'asia',
    'israel': 'asia',
    'japan': 'asia',
    'jordan': 'asia',
    'kazakhstan': 'asia',
    'kuwait': 'asia',
    'kyrgyzstan': 'asia',
    "lao people's democratic republic": 'asia',
    'lebanon': 'asia',
    'malaysia': 'asia',
    'maldives': 'asia',
    'mongolia': 'asia',
    'myanmar': 'asia',
    'nepal': 'asia',
    'oman': 'asia',
    'pakistan': 'asia',
    'philippines': 'asia',
    'qatar': 'asia',
    'saudi arabia': 'asia',
    'singapore': 'asia',
    'south korea': 'asia',
    'sri lanka': 'asia',
    'state of palestine': 'asia',
    'syria': 'asia',
    'taiwan': 'asia',
    'tajikistan': 'asia',
    'thailand': 'asia',
    'timor-leste': 'asia',
    'turkey': 'asia',
    'turkmenistan': 'asia',
    'united arab emirates': 'asia',
    'uzbekistan': 'asia',
    'vietnam': 'asia',
    'yemen': 'asia',

    # central america and caribbean
    'anguilla': 'central america and caribbean',
    'antigua and barbuda': 'central america and caribbean',
    'aruba': 'central america and caribbean',
    'bahamas': 'central america and caribbean',
    'barbados': 'central america and caribbean',
    'belize': 'central america and caribbean',
    'bermuda': 'central america and caribbean',
    'bonaire': 'central america and caribbean',
    'british virgin islands': 'central america and caribbean',
    'cayman islands': 'central america and caribbean',
    'costa rica': 'central america and caribbean',
    'cuba': 'central america and caribbean',
    'curaçao': 'central america and caribbean',
    'dominica': 'central america and caribbean',
    'dominican republic': 'central america and caribbean',
    'el salvador': 'central america and caribbean',
    'grenada': 'central america and caribbean',
    'guadeloupe': 'central america and caribbean',
    'guatemala': 'central america and caribbean',
    'haiti': 'central america and caribbean',
    'honduras': 'central america and caribbean',
    'jamaica': 'central america and caribbean',
    'martinique': 'central america and caribbean',
    'montserrat': 'central america and caribbean',
    'nicaragua': 'central america and caribbean',
    'panama': 'central america and caribbean',
    'puerto rico': 'central america and caribbean',
    'saba': 'central america and caribbean',
    'saint kitts and nevis': 'central america and caribbean',
    'saint lucia': 'central america and caribbean',
    'saint vincent and the grenadines': 'central america and caribbean',
    'saint maarten (dutch part)': 'central america and caribbean',
    'st. eustatius': 'central america and caribbean',
    'trinidad and tobago': 'central america and caribbean',
    'turks and caicos islands': 'central america and caribbean',
    'united states virgin islands': 'central america and caribbean',

    # europe
    'albania': 'europe',
    'andorra': 'europe',
    'austria': 'europe',
    'belarus': 'europe',
    'belgium': 'europe',
    'bosnia and herzegovina': 'europe',
    'bulgaria': 'europe',
    'croatia': 'europe',
    'cyprus': 'europe',
    'czechia': 'europe',
    'denmark': 'europe',
    'estonia': 'europe',
    'finland': 'europe',
    'france': 'europe',
    'germany': 'europe',
    'greece': 'europe',
    'hungary': 'europe',
    'iceland': 'europe',
    'ireland': 'europe',
    'italy': 'europe',
    'latvia': 'europe',
    'liechtenstein': 'europe',
    'lithuania': 'europe',
    'luxembourg': 'europe',
    'malta': 'europe',
    'monaco': 'europe',
    'montenegro': 'europe',
    'netherlands': 'europe',
    'north macedonia': 'europe',
    'norway': 'europe',
    'poland': 'europe',
    'portugal': 'europe',
    'republic of moldova': 'europe',
    'romania': 'europe',
    'russia': 'europe',
    'san marino': 'europe',
    'serbia': 'europe',
    'slovakia': 'europe',
    'slovenia': 'europe',
    'spain': 'europe',
    'sweden': 'europe',
    'switzerland': 'europe',
    'ukraine': 'europe',
    'united kingdom': 'europe',

    # north america
    'canada': 'north america',
    'mexico': 'north america',
    'united states': 'north america',

    # oceania
    'american samoa': 'oceania',
    'australia': 'oceania',
    'cook islands': 'oceania',
    'fiji': 'oceania',
    'french polynesia': 'oceania',
    'guam': 'oceania',
    'kiribati': 'oceania',
    'marshall islands': 'oceania',
    'micronesia': 'oceania',
    'new caledonia': 'oceania',
    'new zealand': 'oceania',
    'niue': 'oceania',
    'northern mariana islands': 'oceania',
    'palau': 'oceania',
    'papua new guinea': 'oceania',
    'samoa': 'oceania',
    'solomon islands': 'oceania',
    'tonga': 'oceania',
    'tuvalu': 'oceania',
    'vanuatu': 'oceania',

    # south america
    'argentina': 'south america',
    'bolivia': 'south america',
    'brazil': 'south america',
    'chile': 'south america',
    'colombia': 'south america',
    'ecuador': 'south america',
    'french guiana': 'south america',
    'guyana': 'south america',
    'paraguay': 'south america',
    'peru': 'south america',
    'suriname': 'south america',
    'uruguay': 'south america',
    'venezuela': 'south america',
}

In [63]:
# creating continent column aligned with turismo.gov dataset
unwto = add_continent_column(unwto, 'country_name', continent_mapping)

In [64]:
# checking value counts in the column continent to see if the mapping worked
value_counts_by_column(unwto)

=== type_of_arrival ===
type_of_arrival
overnight tourist    1518
same-day visitor      897
Name: count, dtype: int64

=== country_name ===
country_name
albania    20
andorra    20
bahamas    20
bahrain    20
canada     20
           ..
qatar       3
iran        2
vietnam     2
yemen       2
russia      1
Name: count, Length: 196, dtype: int64

=== year ===
year
2015    300
2016    298
2017    297
2018    284
2019    283
2020    279
2021    248
2022    215
2023    107
2024    104
Name: count, dtype: int64

=== arrivals ===
arrivals
82000     7
55000     7
2000      7
218000    6
255000    6
         ..
558500    1
387600    1
545000    1
8600      1
31800     1
Name: count, Length: 1926, dtype: int64

=== covid_period ===
covid_period
pre_covid     1462
covid          527
post_covid     426
Name: count, dtype: int64

=== continent ===
continent
europe                           556
central america and caribbean    517
asia                             492
africa                           418
oceania                          229
south america                    146
north america                     57
Name: count, dtype: int64

In [65]:
unwto.isnull().sum()

type_of_arrival    0
country_name       0
year               0
arrivals           0
covid_period       0
continent          0
dtype: int64

# 04. Checking if key colunms have same values in both sets

### Continent Column

In [66]:
# turismo.gov dataset columns
arrivals_10y['continent'].value_counts()

continent
europe                           159153
asia                              86703
south america                     59818
central america and caribbean     50764
africa                            49532
north america                     15283
oceania                           13908
unspecified continent              4277
Name: count, dtype: int64

In [67]:
# UNWTO dataset columns
unwto['continent'].value_counts()

continent
europe                           556
central america and caribbean    517
asia                             492
africa                           418
oceania                          229
south america                    146
north america                     57
Name: count, dtype: int64

### Country Columns

In [68]:
# turismo.gov dataset columns
pd.set_option('display.max_rows', None)
arrivals_10y['country_of_origin'].value_counts()

country_of_origin
others                                       23517
argentina                                     5606
france                                        5312
germany                                       5310
united states                                 5294
colombia                                      5246
spain                                         5238
uruguay                                       5221
italy                                         5213
chile                                         5198
paraguay                                      5197
peru                                          5181
united kingdom                                5121
venezuela                                     5095
switzerland                                   5084
bolivia                                       5064
netherlands                                   5056
canada                                        5005
portugal                                      4993
mexico                                        4984
belgium                                       4953
poland                                        4903
australia                                     4903
russia                                        4899
ecuador                                       4884
china                                         4872
ireland                                       4861
austria                                       4850
japan                                         4824
sweden                                        4816
romania                                       4778
ukraine                                       4771
denmark                                       4761
norway                                        4760
israel                                        4741
dominican republic                            4723
south korea                                   4712
south africa                                  4708
new zealand                                   4700
cuba                                          4692
india                                         4691
greece                                        4683
czechia                                       4677
turkey                                        4670
finland                                       4665
hungary                                       4641
costa rica                                    4633
philippines                                   4621
guatemala                                     4608
morocco                                       4577
panama                                        4570
bulgaria                                      4570
croatia                                       4568
slovakia                                      4565
lithuania                                     4557
honduras                                      4552
el salvador                                   4541
luxembourg                                    4531
guyana                                        4495
malaysia                                      4493
serbia                                        4491
slovenia                                      4488
nicaragua                                     4487
haiti                                         4483
latvia                                        4474
taiwan                                        4471
singapore                                     4457
indonesia                                     4452
estonia                                       4448
trinidad and tobago                           4441
china, hong kong                              4435
thailand                                      4430
suriname                                      4428
cabo verde                                    4419
angola                                        4402
tunisia                                       4402
pakistan                                      4386
lebanon                                       4381
egypt                                         4351
iran                                          4351
nigeria                                       4328
saudi arabia                                  4327
mozambique                                    4317
ghana                                         4312
kenya                                         4294
bangladesh                                    4292
syria                                         4291
unspecified                                   4277
french guiana                                 4203
others from asia                               608
others from africa                             573
others from europe                             563
others from central america and caribbean      374
others from oceania                             48
Name: count, dtype: int64

In [69]:
# UNWTO dataset columns
pd.set_option('display.max_rows', None)
unwto['country_name'].value_counts()

country_name
albania                                       20
andorra                                       20
bahamas                                       20
bahrain                                       20
canada                                        20
chile                                         20
costa rica                                    20
dominican republic                            20
el salvador                                   20
georgia                                       20
china, hong kong                              20
hungary                                       20
indonesia                                     20
israel                                        20
italy                                         20
jordan                                        20
lithuania                                     20
china, macao special administrative region    20
mauritius                                     20
mexico                                        20
oman                                          20
new zealand                                   20
paraguay                                      20
poland                                        20
puerto rico                                   20
saudi arabia                                  20
singapore                                     20
south africa                                  20
spain                                         20
trinidad and tobago                           20
ukraine                                       20
united kingdom                                20
argentina                                     19
barbados                                      18
namibia                                       18
fiji                                          17
monaco                                        17
new caledonia                                 17
united states                                 17
bermuda                                       16
bulgaria                                      16
belarus                                       16
sri lanka                                     16
colombia                                      16
denmark                                       16
dominica                                      16
estonia                                       16
french polynesia                              16
greece                                        16
grenada                                       16
guatemala                                     16
honduras                                      16
jamaica                                       16
martinique                                    16
curaçao                                       16
aruba                                         16
saint maarten (dutch part)                    16
nicaragua                                     16
northern mariana islands                      16
panama                                        16
saint kitts and nevis                         16
anguilla                                      16
saint lucia                                   16
saint vincent and the grenadines              16
eswatini                                      16
turkey                                        16
egypt                                         16
belize                                        15
cayman islands                                15
cyprus                                        15
morocco                                       15
peru                                          15
seychelles                                    15
tonga                                         15
united republic of tanzania                   15
samoa                                         15
azerbaijan                                    14
botswana                                      14
czechia                                       14
france                                        14
iceland                                       14
india                                         14
latvia                                        14
mozambique                                    14
vanuatu                                       14
papua new guinea                              14
philippines                                   14
rwanda                                        14
san marino                                    14
sierra leone                                  14
united arab emirates                          14
turks and caicos islands                      14
united states virgin islands                  14
kiribati                                      13
haiti                                         13
madagascar                                    13
montserrat                                    13
brunei darussalam                             12
myanmar                                       12
benin                                         12
ethiopia                                      12
state of palestine                            12
lao people's democratic republic              12
malaysia                                      12
réunion                                       12
american samoa                                11
british virgin islands                        11
south korea                                   11
antigua and barbuda                           10
armenia                                       10
belgium                                       10
bosnia and herzegovina                        10
brazil                                        10
cuba                                          10
germany                                       10
guam                                          10
ireland                                       10
liechtenstein                                 10
malta                                         10
mongolia                                      10
republic of moldova                           10
nigeria                                       10
marshall islands                              10
portugal                                      10
serbia                                        10
slovenia                                      10
north macedonia                               10
burkina faso                                  10
uruguay                                       10
finland                                        9
kuwait                                         9
togo                                           9
angola                                         8
austria                                        8
bhutan                                         8
bolivia                                        8
cambodia                                       8
cabo verde                                     8
congo                                          8
cook islands                                   8
croatia                                        8
french guiana                                  8
gambia                                         8
ghana                                          8
guadeloupe                                     8
guyana                                         8
kyrgyzstan                                     8
lebanon                                        8
luxembourg                                     8
maldives                                       8
montenegro                                     8
nepal                                          8
netherlands                                    8
niue                                           8
norway                                         8
sweden                                         8
switzerland                                    8
tunisia                                        8
tuvalu                                         8
bangladesh                                     7
solomon islands                                7
chad                                           7
comoros                                        7
democratic republic of the congo               7
malawi                                         7
mali                                           7
timor-leste                                    7
sao tome and principe                          7
thailand                                       7
uganda                                         7
zambia                                         7
central african republic                       6
china                                          6
djibouti                                       6
kenya                                          6
niger                                          6
palau                                          6
senegal                                        6
suriname                                       6
venezuela                                      6
taiwan                                         5
japan                                          5
kazakhstan                                     5
guinea-bissau                                  5
romania                                        5
uzbekistan                                     5
slovakia                                       5
micronesia                                     4
sudan                                          4
burundi                                        3
guinea                                         3
qatar                                          3
iran                                           2
vietnam                                        2
yemen                                          2
russia                                         1
Name: count, dtype: int64

In [70]:
# setting limites back to standard
pd.reset_option('display.max_rows')

# 05. Exporting final data

In [71]:
# exporting clean, wrangled and translated turismo.gov dataset to pickle file
arrivals_10y.to_pickle('../01. Data/02. Processed Data/arrivals_10y.pkl')

In [72]:
# exporting clean, wrangled UNWTO dataset to pickle file
unwto.to_pickle('../01. Data/02. Processed Data/unwto_processed.pkl')

In [73]:
# exporting both datasets to csv as weel, for Tableau
arrivals_10y.to_csv('../01. Data/02. Processed Data/arrivals_10y.csv', index=False)
unwto.to_csv('../01. Data/02. Processed Data/unwto_processed.csv', index=False)