# 01. Importing Libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st

In [2]:
import sys
sys.path.append('..')

from src.functions import *

# 02. Importing data

In [3]:
places = pd.read_csv('../01. Data/01. Raw Data/brazil_tourism_intelligence.csv')

In [4]:
places.head()

,state,state_code,destination,type,best_months,good_months,avoid_months,why_best,category,international_draw,weather,crowd_level,description
0,Maranhão,MA,Lençóis Maranhenses,Nature / Ecotourism,June|July|August,May|September,January|February|March,Rainy season ends but lagoons still full — ide...,Nature / Ecotourism,High,hot,moderate,Vast desert landscape of white sand dunes fill...
1,Mato Grosso do Sul,MS,Pantanal,Wildlife / Ecotourism,July|August|September|October,April|May|June,November|December|January|February|March,Dry season — water levels low so wildlife conc...,Wildlife / Ecotourism,Very High,hot,low,The world's largest tropical wetland — a UNESC...
2,Amazonas,AM,Amazon Rainforest (dry season),Nature / Ecotourism,June|July|August|September,April|May,NaN,Dry season — easier trekking and wildlife spot...,Nature / Ecotourism,Very High,hot,low,"The world's largest rainforest, covering 60% o..."
3,Amazonas,AM,Amazon Rainforest (wet season),Nature / Ecotourism,January|February|March,November|December,NaN,Wet season — easier navigation by boat. Flora ...,Nature / Ecotourism,High,hot,low,Flooded forest season — boats navigate between...
4,Pernambuco,PE,Fernando de Noronha (diving),Marine / Diving,August|September|October|November,December|January,March|April|May,Clearest waters for diving (up to 50m visibili...,Marine / Diving,Very High,warm,moderate,Brazil's most exclusive island destination — a...

In [5]:
places.shape

(51, 13)

# 03. Data discovery, cleaning and wrangling

In [6]:
places.isnull().sum()

state                  0
state_code             0
destination            0
type                   0
best_months            0
good_months           11
avoid_months          20
why_best               0
category               0
international_draw     0
weather                0
crowd_level            0
description            0
dtype: int64

In [7]:
places.duplicated().sum()

np.int64(0)

In [8]:
places.dtypes

state                 str
state_code            str
destination           str
type                  str
best_months           str
good_months           str
avoid_months          str
why_best              str
category              str
international_draw    str
weather               str
crowd_level           str
description           str
dtype: object

In [9]:
# checking unique values in each column and understanding the content of the dataset
for column in places.columns:
    print(f'\n{"="*40}')
    print(f'{column} ({places[column].nunique()} unique values):')
    print(places[column].unique())

========================================
state (26 unique values):
<ArrowStringArray>
[           'Maranhão',  'Mato Grosso do Sul',            'Amazonas',
          'Pernambuco',      'Rio de Janeiro',           'São Paulo',
               'Bahia',               'Ceará',              'Paraná',
        'Minas Gerais', 'Rio Grande do Norte',                'Pará',
      'Santa Catarina',   'Rio Grande do Sul',           'Tocantins',
               'Piauí',         'Mato Grosso',             'Paraíba',
             'Alagoas',             'Sergipe',      'Espírito Santo',
               'Goiás',             'Roraima',                'Acre',
            'Rondônia',               'Amapá']
Length: 26, dtype: str

========================================
state_code (26 unique values):
<ArrowStringArray>
['MA', 'MS', 'AM', 'PE', 'RJ', 'SP', 'BA', 'CE', 'PR', 'MG', 'RN', 'PA', 'SC',
 'RS', 'TO', 'PI', 'MT', 'PB', 'AL', 'SE', 'ES', 'GO', 'RR', 'AC', 'RO', 'AP']
Length: 26, dtype: str

========================================
destination (51 unique values):
<ArrowStringArray>
[                         'Lençóis Maranhenses',
                                     'Pantanal',
               'Amazon Rainforest (dry season)',
               'Amazon Rainforest (wet season)',
                 'Fernando de Noronha (diving)',
                'Fernando de Noronha (surfing)',
                        'Rio de Janeiro (city)',
                    'Rio de Janeiro — Carnaval',
                   'Rio de Janeiro — Réveillon',
                                  'Ilha Grande',
                                       'Búzios',
                             'São Paulo (city)',
             'São Paulo — Formula 1 Grand Prix',
                             'Campos do Jordão',
                                     'Salvador',
                           'Chapada Diamantina',
               'Porto Seguro / Arraial d'Ajuda',
                           'Morro de São Paulo',
                                 'Jericoacoara',
                                    'Fortaleza',
                   'Foz do Iguaçu (dry season)',
                   'Foz do Iguaçu (wet season)',
                                   'Ouro Preto',
                        'Chapada dos Veadeiros',
                                 'Natal / Pipa',
            'Lençóis do Norte (Genipabu dunes)',
                      'Belém — Círio de Nazaré',
                                'Alter do Chão',
                                'Florianópolis',
                       'Blumenau — Oktoberfest',
                             'Gramado / Canela',
                                      'Jalapão',
                            'Serra da Capivara',
                        'Chapada dos Guimarães',
 'Festival Folclórico do Boi Bumbá — Parintins',
                      'Festa Junina — São Luís',
                       'Festa Junina — Caruaru',
                'Festa Junina — Campina Grande',
                                       'Maceió',
                                     'Maragogi',
                              'Canion do Xingó',
                                      'Aracaju',
                                    'Guarapari',
                                   'Pedra Azul',
                                  'Pirenópolis',
                                'Monte Roraima',
                                   'Rio Branco',
                                       'Xapuri',
                                'Guajará-Mirim',
                    'Cabo Orange National Park',
                                     'Oiapoque']
Length: 51, dtype: str

========================================
type (23 unique values):
<ArrowStringArray>
[       'Nature / Ecotourism',      'Wildlife / Ecotourism',
            'Marine / Diving',                    'Surfing',
     'City / Culture / Beach',             'Cultural Event',
             'Island / Beach',                      'Beach',
  'City / Business / Culture',               'Sports Event',
         'Mountain / Culture',          'Trekking / Nature',
           'Beach / Kitesurf',               'City / Beach',
         'Waterfall / Nature',         'Colonial / Culture',
             'Nature / Beach', 'Cultural / Religious Event',
       'River Beach / Nature',               'Beach / City',
             'Archaeological',          'Nature / Trekking',
             'City / Culture']
Length: 23, dtype: str

========================================
best_months (31 unique values):
<ArrowStringArray>
[                                            'June|July|August',
                                'July|August|September|October',
                                   'June|July|August|September',
                                       'January|February|March',
                            'August|September|October|November',
                                             'January|February',
                         'April|May|September|October|November',
                                               'February|March',
                                             'December|January',
                                 'October|November|March|April',
             'October|November|December|January|February|March',
                       'March|April|September|October|November',
                                                     'November',
                                  'February|June|July|December',
                           'June|July|August|September|October',
 'June|July|August|September|October|November|December|January',
                                                  'March|April',
                     'April|June|July|August|September|October',
                               'May|June|July|August|September',
                                             'October|November',
                                     'August|September|October',
                              'December|January|February|March',
                                                      'October',
                                    'June|July|August|December',
                                                    'June|July',
                          'september|october|november|december',
                                   'june|july|august|september',
                           'november|december|january|february',
                              'december|january|february|march',
                                             'june|july|august',
                                'july|august|september|october']
Length: 31, dtype: str

========================================
good_months (27 unique values):
<ArrowStringArray>
[                'May|September',                'April|May|June',
                     'April|May',             'November|December',
              'December|January',                             nan,
               'March|June|July',                 'September|May',
               'September|April',                    'May|August',
                           'All',                  'May|November',
                           'May',                   'May|October',
            'June|July|December',                'March|November',
                 'April|October',                 'July|November',
                'November|April', 'january|february|march|august',
             'april|may|october',       'january|february|august',
                 'march|october',    'april|may|october|november',
                'november|april',                 'may|september',
                   'may|october',                 'june|november']
Length: 28, dtype: str

========================================
avoid_months (15 unique values):
<ArrowStringArray>
[                  'January|February|March',
 'November|December|January|February|March',
                                        nan,
                          'March|April|May',
                         'January|February',
                         'June|July|August',
                    'January|February|July',
                     'May|June|July|August',
             'January|February|March|April',
                            'may|june|july',
                'december|january|february',
                                'june|july',
                         'june|july|august',
       'november|december|january|february',
          'december|january|february|march',
             'january|february|march|april']
Length: 16, dtype: str

========================================
why_best (51 unique values):
<ArrowStringArray>
[                                                                            'Rainy season ends but lagoons still full — ideal for swimming and sandboarding',
                                                                       'Dry season — water levels low so wildlife concentrates. Best jaguar spotting Jul-Oct',
                                                                           'Dry season — easier trekking and wildlife spotting. Beaches appear on riverbanks',
                                                                                'Wet season — easier navigation by boat. Flora at peak. Different experience',
                                                                        'Clearest waters for diving (up to 50m visibility). Spinner dolphins. Fewer tourists',
                                                                                                         'Strong waves on the Atlantic side — surfing season',
                                                                                                      'Shoulder season — warm but less crowded. Lower prices',
                                                                                                           'World-famous Carnaval — major international draw',
                                                                                                               'One of world's largest New Year celebrations',
                                                                                                    'Warm water and less rain. Avoid winter — cold and rainy',
                                                                                                                    'Warm summer months. Peak season Dec-Feb',
                                                                                                            'Mild weather. Avoid summer heat and winter cold',
                                                                                                       'Major international sports event — peak hotel demand',
                                                                                             'Winter months — cool mountain air. Festival de Inverno in July',
                                                                                      'Carnaval in Feb is world-class. June is Festa Junina. Dec for beaches',
                                                                                     'Dry season — waterfalls still flowing but trails dry. Great visibility',
                                                                                                                        'Warm and sunny. Peak season Dec-Feb',
                                                                                                             'Summer warmth and clear water. Car-free island',
                                                                                     'Dry season with consistent winds — world-class kitesurfing destination',
                                                                                                          'Dry season — sunny and breezy. Avoid rainy season',
                                                                                              'Best visibility and hiking conditions. Falls still impressive',
                                                                                                      'Maximum water flow — most dramatic and powerful falls',
                                                                           'Dry season — cobblestone streets walkable. Semana Santa in April is world-famous',
                                                                                                  'Dry season — trails accessible. Waterfalls at good levels',
                                                                               'Dry season — sunny and calm. Pipa is one of Brazil's most scenic beach towns',
                                                                                                     'Dry season — dunes accessible and buggy rides possible',
                                                                                           'Largest religious procession in the world — major cultural event',
                                                                                       'Dry season — river beaches appear. Crystal clear water in the Amazon',
                                                                                                               'Southern hemisphere summer — warm and lively',
                                                                                                                    'Second largest Oktoberfest in the world',
                                                                                   'Winter for European-style cold and Christmas festival. Summer for nature',
                                                                               'Dry season — fervedouros (natural pools) accessible. Off-the-beaten-path gem',
                                                                                         'Dry season — rock art sites accessible. UNESCO World Heritage Site',
                                                                              'Dry season — trails accessible. Spectacular canyon and waterfalls near Cuiabá',
 'Largest folkloric festival in the Amazon — held in Parintins island. Two competing groups (Garantido vs Caprichoso). Major international draw growing fast',
                                 'São Luís hosts one of the most traditional Festa Juninas — deeply rooted in Maranhão culture with bumba-meu-boi traditions',
                                  'Caruaru is considered the capital of Festa Junina — one of the largest in the world. UNESCO recognized cultural tradition',
                                                     'Campina Grande's Festa Junina rivals Caruaru — lasts the entire month of June and draws massive crowds',
                                                                      'Calm, warm urban beaches year-round. Dry season brings clearest water and least rain.',
                                                             'Natural reef pools (galés) are at their clearest in the dry season when visibility is highest.',
                                       'Dry season makes canyon boat tours ideal — water levels are lower revealing the canyon walls at their most dramatic.',
                                                           'Dry season brings calm, clear water to Aracaju's beaches. The city is compact and very walkable.',
                                                                'Summer brings warm water and long sunny days. Beaches are calmer than Rio with less crowds.',
                                                'Dry season brings clear skies that showcase the granite dome and surrounding Atlantic Forest at their best.',
                                              'Dry season is ideal for hiking to the many waterfalls nearby and exploring the historic streets without rain.',
                                            'Wet season paradoxically is best — the tepui is always misty but rivers are passable and the landscape is lush.',
                                                                         'Dry season prevents flooding and makes forest trails and river access much easier.',
                                                                'Dry season opens up forest trails in the Chico Mendes Reserve and makes river travel safer.',
                                                              'Dry season lowers river levels exposing beaches and making boat trips and fishing far better.',
                                            'Dry season is the only practical time to visit — access roads and boat routes are impassable in the wet season.',
                                                                'Dry season makes the road from Macapá passable and border crossing to French Guiana easier.']
Length: 51, dtype: str

========================================
category (21 unique values):
<ArrowStringArray>
[       'Nature / Ecotourism',      'Wildlife / Ecotourism',
            'Marine / Diving',                    'Surfing',
     'City / Culture / Beach',             'Cultural Event',
             'Island / Beach',                      'Beach',
  'City / Business / Culture',               'Sports Event',
         'Mountain / Culture',          'Trekking / Nature',
           'Beach / Kitesurf',               'City / Beach',
         'Waterfall / Nature',         'Colonial / Culture',
             'Nature / Beach', 'Cultural / Religious Event',
       'River Beach / Nature',               'Beach / City',
             'Archaeological']
Length: 21, dtype: str

========================================
international_draw (5 unique values):
<ArrowStringArray>
['High', 'Very High', 'Medium', 'Low', 'Moderate']
Length: 5, dtype: str

========================================
weather (4 unique values):
<ArrowStringArray>
['hot', 'warm', 'mild', 'cool']
Length: 4, dtype: str

========================================
crowd_level (4 unique values):
<ArrowStringArray>
['moderate', 'low', 'high', 'very high']
Length: 4, dtype: str

========================================
description (51 unique values):
<ArrowStringArray>
[                                                                                                    'Vast desert landscape of white sand dunes filled with crystal-clear freshwater lagoons after the rainy season. A surreal and unique ecosystem found nowhere else on Earth.',
                                                                       'The world's largest tropical wetland — a UNESCO World Heritage Site and the best place on Earth to spot jaguars in the wild. Also home to giant otters, capybaras, caimans and hundreds of bird species.',
                                                                               'The world's largest rainforest, covering 60% of Brazil. Dry season offers easier trekking, river beaches and exceptional wildlife spotting. Base yourself in Manaus for access to jungle lodges.',
                                                                                                          'Flooded forest season — boats navigate between treetops in the iconic igapó (flooded forest). Pink river dolphins are more visible and the landscape is otherworldly.',
                                                                          'Brazil's most exclusive island destination — a UNESCO marine reserve 350km offshore with the clearest waters in the South Atlantic. World-class diving with spinner dolphins, sea turtles and sharks.',
                                                                                                                                    'Baía dos Porcos and Cacimba do Padre host internationally renowned surf breaks. The island limits visitor numbers to protect the ecosystem.',
                                                                                         'Brazil's most iconic city — home to Christ the Redeemer, Copacabana, Ipanema, and the Sugarloaf Mountain. A vibrant mix of beach culture, samba, gastronomy and world-class nightlife.',

In [10]:
# drpping columns that seem to be duplicated
places.drop(columns=['category'], inplace=True)

In [11]:
# Renaming columns for better handling
places.rename(columns={'type': 'tourism_type'}, inplace=True)

In [12]:
# checking all lines for discrepancies in data (except why best and description, which will be checked separately)
places.drop(columns=['why_best', 'description'])

,state,state_code,destination,tourism_type,best_months,good_months,avoid_months,international_draw,weather,crowd_level
0,Maranhão,MA,Lençóis Maranhenses,Nature / Ecotourism,June|July|August,May|September,January|February|March,High,hot,moderate
1,Mato Grosso do Sul,MS,Pantanal,Wildlife / Ecotourism,July|August|September|October,April|May|June,November|December|January|February|March,Very High,hot,low
2,Amazonas,AM,Amazon Rainforest (dry season),Nature / Ecotourism,June|July|August|September,April|May,NaN,Very High,hot,low
3,Amazonas,AM,Amazon Rainforest (wet season),Nature / Ecotourism,January|February|March,November|December,NaN,High,hot,low
4,Pernambuco,PE,Fernando de Noronha (diving),Marine / Diving,August|September|October|November,December|January,March|April|May,Very High,warm,moderate
5,Pernambuco,PE,Fernando de Noronha (surfing),Surfing,January|February,NaN,NaN,High,warm,moderate
6,Rio de Janeiro,RJ,Rio de Janeiro (city),City / Culture / Beach,April|May|September|October|November,March|June|July,January|February,Very High,warm,high
7,Rio de Janeiro,RJ,Rio de Janeiro — Carnaval,Cultural Event,February|March,NaN,NaN,Very High,warm,very high
8,Rio de Janeiro,RJ,Rio de Janeiro — Réveillon,Cultural Event,December|January,NaN,NaN,Very High,warm,very high
9,Rio de Janeiro,RJ,Ilha Grande,Island / Beach,October|November|March|April,September|May,June|July|August,High,warm,moderate
10,Rio de Janeiro,RJ,Búzios,Beach,October|November|December|January|February|March,September|April,June|July|August,High,hot,high
11,São Paulo,SP,São Paulo (city),City / Business / Culture,March|April|September|October|November,May|August,January|February|July,Very High,mild,high
12,São Paulo,SP,São Paulo — Formula 1 Grand Prix,Sports Event,November,NaN,NaN,Very High,mild,very high
13,São Paulo,SP,Campos do Jordão,Mountain / Culture,June|July|August,May|September,NaN,Medium,cool,moderate
14,Bahia,BA,Salvador,City / Culture / Beach,February|June|July|December,All,NaN,Very High,hot,high
15,Bahia,BA,Chapada Diamantina,Trekking / Nature,June|July|August|September|October,May|November,January|February|March,High,warm,low
16,Bahia,BA,Porto Seguro / Arraial d'Ajuda,Beach,October|November|December|January|February|March,September|April,NaN,High,hot,high
17,Bahia,BA,Morro de São Paulo,Island / Beach,October|November|December|January|February|March,September|April,May|June|July|August,High,hot,moderate
18,Ceará,CE,Jericoacoara,Beach / Kitesurf,June|July|August|September|October|November|De...,May,NaN,Very High,hot,moderate
19,Ceará,CE,Fortaleza,City / Beach,June|July|August|September,May|October,January|February|March,High,hot,high
20,Paraná,PR,Foz do Iguaçu (dry season),Waterfall / Nature,August|September|October|November,June|July|December,January|February|March,Very High,warm,high
21,Paraná,PR,Foz do Iguaçu (wet season),Waterfall / Nature,March|April,NaN,NaN,Very High,warm,moderate
22,Minas Gerais,MG,Ouro Preto,Colonial / Culture,April|June|July|August|September|October,March|November,NaN,High,mild,moderate
23,Minas Gerais,MG,Chapada dos Veadeiros,Trekking / Nature,May|June|July|August|September,April|October,November|December|January|February|March,Medium,warm,low
24,Rio Grande do Norte,RN,Natal / Pipa,Beach,June|July|August|September|October,May|November,January|February|March,High,hot,moderate
25,Rio Grande do Norte,RN,Lençóis do Norte (Genipabu dunes),Nature / Beach,June|July|August|September,May|October,NaN,Medium,hot,moderate
26,Pará,PA,Belém — Círio de Nazaré,Cultural / Religious Event,October|November,NaN,NaN,High,hot,very high
27,Pará,PA,Alter do Chão,River Beach / Nature,August|September|October,July|November,January|February|March|April,High,hot,low
28,Santa Catarina,SC,Florianópolis,Beach / City,December|January|February|March,November|April,June|July|August,High,warm,high
29,Santa Catarina,SC,Blumenau — Oktoberfest,Cultural Event,October,NaN,NaN,High,mild,very high
30,Rio Grande do Sul,RS,Gramado / Canela,Mountain / Culture,June|July|August|December,May|September,NaN,Medium,cool,moderate
31,Tocantins,TO,Jalapão,Trekking / Nature,May|June|July|August|September,April|October,November|December|January|February|March,Medium,hot,low
32,Piauí,PI,Serra da Capivara,Archaeological,May|June|July|August|September,April|October,November|December|January|February|March,Low,hot,low
33,Mato Grosso,MT,Chapada dos Guimarães,Trekking / Nature,May|June|July|August|September,April|October,November|December|January|February|March,Medium,warm,low
34,Amazonas,AM,Festival Folclórico do Boi Bumbá — Parintins,Cultural Event,June|July,NaN,NaN,High,hot,very high
35,Maranhão,MA,Festa Junina — São Luís,Cultural Event,June|July,NaN,NaN,High,hot,high
36,Pernambuco,PE,Festa Junina — Caruaru,Cultural Event,June|July,NaN,NaN,High,hot,very high
37,Paraíba,PB,Festa Junina — Campina Grande,Cultural Event,June|July,NaN,NaN,High,hot,very high
38,Alagoas,AL,Maceió,Beach,september|october|november|december,january|february|march|august,may|june|july,Moderate,hot,moderate
39,Alagoas,AL,Maragogi,Beach,september|october|november|december,january|february|march|august,may|june|july,High,hot,moderate
40,Sergipe,SE,Canion do Xingó,Nature / Trekking,june|july|august|september,april|may|october,december|january|february,Low,hot,low
41,Sergipe,SE,Aracaju,Beach,september|october|november|december,january|february|august,may|june|july,Low,hot,low
42,Espírito Santo,ES,Guarapari,Beach,november|december|january|february,march|october,june|july,Low,warm,moderate
43,Espírito Santo,ES,Pedra Azul,Nature / Trekking,june|july|august|september,april|may|october|november,december|january|february,Low,mild,low
44,Goiás,GO,Pirenópolis,Colonial / Culture,june|july|august|september,april|may|october,december|january|february,Low,mild,low
45,Roraima,RR,Monte Roraima,Trekking / Nature,december|january|february|march,november|april,june|july|august,Very High,cool,low
46,Acre,AC,Rio Branco,Nature / Ecotourism,june|july|august,may|september,november|december|january|february,Low,hot,low
47,Acre,AC,Xapuri,Nature / Ecotourism,june|july|august,may|september,november|december|january|february,Low,hot,low
48,Rondônia,RO,Guajará-Mirim,River Beach / Nature,june|july|august|september,may|october,december|january|february|march,Low,hot,low
49,Amapá,AP,Cabo Orange National Park,Nature / Ecotourism,july|august|september|october,june|november,january|february|march|april,Low,hot,low
50,Amapá,AP,Oiapoque,City / Culture,july|august|september|october,june|november,january|february|march|april,Low,hot,low

In [13]:
# checking destinations, why best and descriptions make sense
for i, row in places.iterrows():
    print(f"--- {i} | {row['destination']} ---")
    print(f"WHY BEST: {row['why_best']}")
    print(f"DESCRIPTION: {row['description']}")
    print()

--- 0 | Lençóis Maranhenses ---
WHY BEST: Rainy season ends but lagoons still full — ideal for swimming and sandboarding
DESCRIPTION: Vast desert landscape of white sand dunes filled with crystal-clear freshwater lagoons after the rainy season. A surreal and unique ecosystem found nowhere else on Earth.

--- 1 | Pantanal ---
WHY BEST: Dry season — water levels low so wildlife concentrates. Best jaguar spotting Jul-Oct
DESCRIPTION: The world's largest tropical wetland — a UNESCO World Heritage Site and the best place on Earth to spot jaguars in the wild. Also home to giant otters, capybaras, caimans and hundreds of bird species.

--- 2 | Amazon Rainforest (dry season) ---
WHY BEST: Dry season — easier trekking and wildlife spotting. Beaches appear on riverbanks
DESCRIPTION: The world's largest rainforest, covering 60% of Brazil. Dry season offers easier trekking, river beaches and exceptional wildlife spotting. Base yourself in Manaus for access to jungle lodges.

--- 3 | Amazon Rainforest (wet season) ---
WHY BEST: Wet season — easier navigation by boat. Flora at peak. Different experience
DESCRIPTION: Flooded forest season — boats navigate between treetops in the iconic igapó (flooded forest). Pink river dolphins are more visible and the landscape is otherworldly.

--- 4 | Fernando de Noronha (diving) ---
WHY BEST: Clearest waters for diving (up to 50m visibility). Spinner dolphins. Fewer tourists
DESCRIPTION: Brazil's most exclusive island destination — a UNESCO marine reserve 350km offshore with the clearest waters in the South Atlantic. World-class diving with spinner dolphins, sea turtles and sharks.

--- 5 | Fernando de Noronha (surfing) ---
WHY BEST: Strong waves on the Atlantic side — surfing season
DESCRIPTION: Baía dos Porcos and Cacimba do Padre host internationally renowned surf breaks. The island limits visitor numbers to protect the ecosystem.

--- 6 | Rio de Janeiro (city) ---
WHY BEST: Shoulder season — warm but less crowded. Lower prices
DESCRIPTION: Brazil's most iconic city — home to Christ the Redeemer, Copacabana, Ipanema, and the Sugarloaf Mountain. A vibrant mix of beach culture, samba, gastronomy and world-class nightlife.

--- 7 | Rio de Janeiro — Carnaval ---
WHY BEST: World-famous Carnaval — major international draw
DESCRIPTION: The world's biggest carnival — five days of samba school parades at the Sambódromo plus street parties (blocos) across the city. An unmissable cultural spectacle.

--- 8 | Rio de Janeiro — Réveillon ---
WHY BEST: One of world's largest New Year celebrations
DESCRIPTION: The world's largest New Year's Eve celebration on Copacabana beach — over 2 million people in white gather for fireworks, live music and offerings to Iemanjá.

--- 9 | Ilha Grande ---
WHY BEST: Warm water and less rain. Avoid winter — cold and rainy
DESCRIPTION: Car-free island off the Rio coast — lush Atlantic forest, pristine beaches and no roads. Accessible only by boat. One of the most biodiverse coastal areas in Brazil.

--- 10 | Búzios ---
WHY BEST: Warm summer months. Peak season Dec-Feb
DESCRIPTION: Chic coastal resort town made famous by Brigitte Bardot in the 1960s. 23 beaches, upscale restaurants and a lively nightlife strip on Rua das Pedras.

--- 11 | São Paulo (city) ---
WHY BEST: Mild weather. Avoid summer heat and winter cold
DESCRIPTION: South America's largest city and Brazil's cultural and economic capital. World-class gastronomy, museums, architecture and the most diverse international community in the country.

--- 12 | São Paulo — Formula 1 Grand Prix ---
WHY BEST: Major international sports event — peak hotel demand
DESCRIPTION: The Brazilian Grand Prix at Interlagos is one of Formula 1's most beloved races — a fast, twisty circuit with passionate crowds and unpredictable weather.

--- 13 | Campos do Jordão ---
WHY BEST: Winter months — cool mountain air. Festival de Inverno in July
DESCRIPTION: Brazil's highest city at 1,628m in the Serra da Mantiqueira — known as the "Brazilian Switzerland". Famous for its European-style architecture, fondue, and winter festival of classical music.

--- 14 | Salvador ---
WHY BEST: Carnaval in Feb is world-class. June is Festa Junina. Dec for beaches
DESCRIPTION: The heart of Afro-Brazilian culture — a UNESCO World Heritage city with the largest African diaspora population outside Africa. Famous for its Pelourinho historic centre, candomblé, and Carnaval.

--- 15 | Chapada Diamantina ---
WHY BEST: Dry season — waterfalls still flowing but trails dry. Great visibility
DESCRIPTION: Stunning highland plateau in Bahia with waterfalls, caves, natural pools and dramatic canyon landscapes. A favourite for multi-day trekking and adventure tourism.

--- 16 | Porto Seguro / Arraial d'Ajuda ---
WHY BEST: Warm and sunny. Peak season Dec-Feb
DESCRIPTION: Where Brazil was first discovered by the Portuguese in 1500. Beautiful beaches, a historic colonial town and a vibrant backpacker scene. One of Brazil's most popular summer destinations.

--- 17 | Morro de São Paulo ---
WHY BEST: Summer warmth and clear water. Car-free island
DESCRIPTION: Car-free island in Bahia accessible only by boat or small plane. Tropical beaches, clear water and a relaxed bohemian atmosphere.

--- 18 | Jericoacoara ---
WHY BEST: Dry season with consistent winds — world-class kitesurfing destination
DESCRIPTION: Remote beach village in Ceará surrounded by dunes, lagoons and mangroves. Famous for kitesurfing, sunset viewpoints and the unique freshwater lagoon of Lagoa do Paraíso.

--- 19 | Fortaleza ---
WHY BEST: Dry season — sunny and breezy. Avoid rainy season
DESCRIPTION: Ceará's vibrant capital — lively beach promenade, excellent seafood, forró music and access to the stunning beaches of the Ceará coast.

--- 20 | Foz do Iguaçu (dry season) ---
WHY BEST: Best visibility and hiking conditions. Falls still impressive
DESCRIPTION: The most spectacular waterfall system in the world — 275 individual falls stretching 2.7km on the border of Brazil, Argentina and Paraguay. Dry season offers easier access and better walkways.

--- 21 | Foz do Iguaçu (wet season) ---
WHY BEST: Maximum water flow — most dramatic and powerful falls
DESCRIPTION: Wet season brings dramatically higher water volume — the falls are at their most powerful and thunderous. The spray can be seen from kilometres away.

--- 22 | Ouro Preto ---
WHY BEST: Dry season — cobblestone streets walkable. Semana Santa in April is world-famous
DESCRIPTION: Brazil's finest example of Baroque colonial architecture — a UNESCO World Heritage city built on gold rush wealth in the 18th century. Cobblestone streets, hilltop churches and excellent cachaça.

--- 23 | Chapada dos Veadeiros ---
WHY BEST: Dry season — trails accessible. Waterfalls at good levels
DESCRIPTION: High-altitude cerrado plateau in Goiás — one of Brazil's oldest and most biodiverse regions. Famous for its powerful waterfalls, quartz crystal rocks and spiritual tourism.

--- 24 | Natal / Pipa ---
WHY BEST: Dry season — sunny and calm. Pipa is one of Brazil's most scenic beach towns
DESCRIPTION: Natal is famous for the largest cashew tree in the world and its sand dune buggy rides. Nearby Pipa is a bohemian cliff-top village with stunning beaches and dolphin-watching.

--- 25 | Lençóis do Norte (Genipabu dunes) ---
WHY BEST: Dry season — dunes accessible and buggy rides possible
DESCRIPTION: Massive coastal dunes near Natal where visitors ride camels and do dune buggy tours. Genipabu lagoon sits dramatically between the dunes and the sea.

--- 26 | Belém — Círio de Nazaré ---
WHY BEST: Largest religious procession in the world — major cultural event
DESCRIPTION: The largest religious procession in the world — over 2 million people follow the image of Our Lady of Nazaré through the streets of Belém every October. The city is also the gateway to the Amazon.

--- 27 | Alter do Chão ---
WHY BEST: Dry season — river beaches appear. Crystal clear water in the Amazon
DESCRIPTION: Known as the "Caribbean of the Amazon" — freshwater beaches of white sand appear along the Tapajós River in the dry season. Crystal-clear water and virtually no international crowds.

--- 28 | Florianópolis ---
WHY BEST: Southern hemisphere summer — warm and lively
DESCRIPTION: The island capital of Santa Catarina — 100 beaches ranging from surf spots to calm lagoons. Popular with Argentine tourists in summer and known for its high quality of life.

--- 29 | Blumenau — Oktoberfest ---
WHY BEST: Second largest Oktoberfest in the world
DESCRIPTION: The largest Oktoberfest outside Germany — held in a city founded by German immigrants in 1850. Three weeks of beer, bratwurst, traditional music and folk dancing.

--- 30 | Gramado / Canela ---
WHY BEST: Winter for European-style cold and Christmas festival. Summer for nature
DESCRIPTION: Charming mountain towns in Rio Grande do Sul with strong German and Italian heritage. Famous for Christmas festival with elaborate decorations, fondue, chocolate and cooler temperatures.

--- 31 | Jalapão ---
WHY BEST: Dry season — fervedouros (natural pools) accessible. Off-the-beaten-path gem
DESCRIPTION: One of Brazil's most remote and spectacular destinations — golden sand dunes, turquoise fervedouros (natural hot springs), and wild rivers in the Tocantins cerrado. Very low tourist numbers.

--- 32 | Serra da Capivara ---
WHY BEST: Dry season — rock art sites accessible. UNESCO World Heritage Site
DESCRIPTION: UNESCO World Heritage Site in Piauí — home to the oldest evidence of human presence in the Americas (over 50,000 years old) with thousands of prehistoric rock paintings.

--- 33 | Chapada dos Guimarães ---
WHY BEST: Dry season — trails accessible. Spectacular canyon and waterfalls near Cuiabá
DESCRIPTION: A dramatic highland plateau near Cuiabá in Mato Grosso — the geodesic centre of South America. Stunning waterfalls, canyons and cerrado landscapes.

--- 34 | Festival Folclórico do Boi Bumbá — Parintins ---
WHY BEST: Largest folkloric festival in the Amazon — held in Parintins island. Two competing groups (Garantido vs Caprichoso). Major international draw growing fast
DESCRIPTION: The second largest festival in Brazil after Carnaval — a spectacular folkloric competition between two rival groups (Garantido and Caprichoso) held on a floating arena in the Amazon river city of Parintins.

--- 35 | Festa Junina — São Luís ---
WHY BEST: São Luís hosts one of the most traditional Festa Juninas — deeply rooted in Maranhão culture with bumba-meu-boi traditions
DESCRIPTION: Maranhão hosts Brazil's most authentic Festa Junina celebrations — the Bumba Meu Boi festival is a UNESCO Intangible Cultural Heritage with elaborate costumes and traditional music.

--- 36 | Festa Junina — Caruaru ---
WHY BEST: Caruaru is considered the capital of Festa Junina — one of the largest in the world. UNESCO recognized cultural tradition
DESCRIPTION: Pernambuco's Caruaru hosts what UNESCO recognised as the world's largest Festa Junina — forró music, traditional dancing, regional food and crafts in the heart of the sertão.

--- 37 | Festa Junina — Campina Grande ---
WHY BEST: Campina Grande's Festa Junina rivals Caruaru — lasts the entire month of June and draws massive crowds
DESCRIPTION: Paraíba's Campina Grande rivals Caruaru for the title of world's largest Festa Junina — 30 days of forró, quadrilha dancing and regional culture.

--- 38 | Maceió ---
WHY BEST: Calm, warm urban beaches year-round. Dry season brings clearest water and least rain.
DESCRIPTION: Alagoas's vibrant capital with beautiful urban beaches, a lively waterfront and excellent seafood. The calm, emerald-green waters make it one of Brazil's most pleasant beach cities.

--- 39 | Maragogi ---
WHY BEST: Natural reef pools (galés) are at their clearest in the dry season when visibility is highest.
DESCRIPTION: Known as the Caribbean of Brazil — natural reef pools called galés create stunning turquoise lagoons of extraordinary clarity. One of Brazil's most photographed coastal destinations.

--- 40 | Canion do Xingó ---
WHY BEST: Dry season makes canyon boat tours ideal — water levels are lower revealing the canyon walls at their most dramatic.
DESCRIPTION: A dramatic narrow gorge carved by the São Francisco River between Sergipe and Alagoas — best explored by boat. Towering canyon walls, turquoise water and virtually no international crowds.

--- 41 | Aracaju ---
WHY BEST: Dry season brings calm, clear water to Aracaju's beaches. The city is compact and very walkable.
DESCRIPTION: Brazil's most compact and walkable state capital — uncrowded beaches, a beautiful waterfront promenade and excellent local seafood. A hidden gem compared to more famous northeastern cities.

--- 42 | Guarapari ---
WHY BEST: Summer brings warm water and long sunny days. Beaches are calmer than Rio with less crowds.
DESCRIPTION: Famous for its monazite sand beaches and calm, warm waters. One of Espírito Santo's most popular beach destinations — less crowded than Rio with a relaxed coastal atmosphere.

--- 43 | Pedra Azul ---
WHY BEST: Dry season brings clear skies that showcase the granite dome and surrounding Atlantic Forest at their best.
DESCRIPTION: A spectacular bare granite dome rising 1,822m from the Atlantic Forest — one of Espírito Santo's most dramatic landscapes. Surrounded by waterfalls, trails and a charming mountain tourism infrastructure.

--- 44 | Pirenópolis ---
WHY BEST: Dry season is ideal for hiking to the many waterfalls nearby and exploring the historic streets without rain.
DESCRIPTION: One of Brazil's best-preserved colonial towns — cobblestone streets, 18th-century churches and dozens of waterfalls within easy reach. A favourite weekend escape from Brasília with a strong arts and music scene.

--- 45 | Monte Roraima ---
WHY BEST: Wet season paradoxically is best — the tepui is always misty but rivers are passable and the landscape is lush.
DESCRIPTION: One of the world's most extraordinary trekking destinations — a flat-topped tepui mountain that inspired Arthur Conan Doyle's The Lost World. Sits at the triple border of Brazil, Venezuela and Guyana. Accessible only through the Raposa Serra do Sol indigenous territory.

--- 46 | Rio Branco ---
WHY BEST: Dry season prevents flooding and makes forest trails and river access much easier.
DESCRIPTION: Capital of Acre and gateway to deep Amazon ecotourism. Home to the legacy of Chico Mendes — the rubber tapper martyr whose fight for the Amazon is preserved in museums and reserves here.

--- 47 | Xapuri ---
WHY BEST: Dry season opens up forest trails in the Chico Mendes Reserve and makes river travel safer.
DESCRIPTION: Small Amazon town where Chico Mendes lived and was assassinated — a pilgrimage site for environmentalists. Authentic rubber tapper culture, forest trails and one of Brazil's most off-the-beaten-path experiences.

--- 48 | Guajará-Mirim ---
WHY BEST: Dry season lowers river levels exposing beaches and making boat trips and fishing far better.
DESCRIPTION: Remote frontier town on the Bolivian border — a gateway to pristine Amazon rivers and forest. Famous for river fishing, boat trips and the historic Madeira-Mamoré railway museum.

--- 49 | Cabo Orange National Park ---
WHY BEST: Dry season is the only practical time to visit — access roads and boat routes are impassable in the wet season.
DESCRIPTION: Brazil's northernmost national park — remote Amazon estuary with mangroves, sea turtles and exceptional birdlife. Virtually no tourists. One of Brazil's last true wilderness frontiers.

--- 50 | Oiapoque ---
WHY BEST: Dry season makes the road from Macapá passable and border crossing to French Guiana easier.
DESCRIPTION: The northernmost city in Brazil — on the border with French Guiana across the Oiapoque River. A unique frontier town where Brazil meets the French-speaking Caribbean world.

In [14]:
# making the necessary changes to the description column to make it more readable and useful for the app
places.loc[2, 'why_best'] = "The world's largest rainforest. Dry season offers easier trekking, river beaches and exceptional wildlife spotting. Base yourself in Manaus for access to jungle lodges"

places.loc[3, 'description'] = "Flooded forest season — boats navigate between treetops in the iconic igapó (flooded forest). Pink river dolphins (locally known as Boto Cor-de-rosa) are more visible and the landscape is otherworldly."

places.loc[4, 'description'] = "Brazil's most exclusive island destination — a UNESCO marine reserve 350km offshore with the clearest waters in the South Atlantic. World-class diving with spinner dolphins, sea turtles and sharks. The island limits visitor numbers to protect the ecosystem."

places.loc[7, 'description'] = "The world's biggest carnival — five days of samba school parades at the Sambódromo plus street parties (blocos) across the city, filled with music and dance and vibrant costumes. An unmissable cultural spectacle."

places.loc[8, 'description'] = "The world's largest New Year's Eve celebration on Copacabana beach — over 2 million people in white gather for fireworks, live music and offerings to Iemanjá, the Afro-Brazilian goddess of the sea."

places.loc[9, 'why_best'] = "Warm water and less rain"

places.loc[10, 'why_best'] = "Warm summer months"

places.loc[11, 'why_best'] = "Mild weather"

places.loc[12, 'why_best'] = "Major international sports event"

places.loc[13, 'why_best'] = "Winter months — cool mountain air. Festival de Inverno in July features music, dance and theatre performances in the historic city centre"

places.loc[16, 'why_best'] = " Warm and sunny weather, ideal for beach activities"

places.loc[19, 'why_best'] = "Dry season — sunny and breezy"

places.loc[34, 'description'] = "The second largest festival in Brazil after Carnaval — a spectacular folkloric competition between two rival groups, each representing a folkloric bull: Garantido (red bull) and Caprichoso (blue bull). The competition is held on a floating arena in the Amazon river city of Parintins and draws visitors from across Brazil and abroad."

In [15]:
# checking the changes in random idexes
places.loc[11]

state                                                         São Paulo
state_code                                                           SP
destination                                            São Paulo (city)
tourism_type                                  City / Business / Culture
best_months                      March|April|September|October|November
good_months                                                  May|August
avoid_months                                      January|February|July
why_best                                                   Mild weather
international_draw                                            Very High
weather                                                            mild
crowd_level                                                        high
description           South America's largest city and Brazil's cult...
Name: 11, dtype: str

In [16]:
#creating new columns with category for app questions
category_map = {
    'Nature / Ecotourism': 'nature',
    'Wildlife / Ecotourism': 'nature',
    'Trekking / Nature': 'nature',
    'Waterfall / Nature': 'nature',
    'River Beach / Nature': 'nature',
    'Nature / Beach': 'nature',
    'Marine / Diving': 'beach',
    'Surfing': 'beach',
    'Island / Beach': 'beach',
    'Beach': 'beach',
    'Beach / Kitesurf': 'beach',
    'City / Beach': 'beach',
    'Beach / City': 'beach',
    'City / Culture / Beach': 'culture',
    'Cultural Event': 'culture',
    'City / Business / Culture': 'city',
    'Mountain / Culture': 'culture',
    'Colonial / Culture': 'culture',
    'Cultural / Religious Event': 'culture',
    'Archaeological': 'culture',
    'Sports Event': 'adventure',
    'Nature / Trekking': 'adventure',
    'City / Culture': 'culture',
}

places['category'] = places['tourism_type'].map(category_map)

In [17]:
# checking new values in the category column
places['category'].unique()

<ArrowStringArray>
['nature', 'beach', 'culture', 'city', 'adventure']
Length: 5, dtype: str

In [18]:
# making the month columsn more readable and consistent for the app
places['best_months'] = places['best_months'].apply(format_months)
places['good_months'] = places['good_months'].apply(format_months)
places['avoid_months'] = places['avoid_months'].apply(format_months)

In [21]:
# checking the changes in the columns
for column in ['best_months', 'good_months', 'avoid_months']:
    print(f'\n{"="*40}')
    print(f'{column} ({places[column].nunique()} unique values):')
    print(places[column].unique())

========================================
best_months (27 unique values):
<ArrowStringArray>
[                                                      'June | July | August',
                                        'July | August | September | October',
                                           'June | July | August | September',
                                                 'January | February | March',
                                    'August | September | October | November',
                                                         'January | February',
                               'April | May | September | October | November',
                                                           'February | March',
                                                         'December | January',
                                         'October | November | March | April',
                 'October | November | December | January | February | March',
                             'March | April | September | October | November',
                                                                   'November',
                                          'February | June | July | December',
                                 'June | July | August | September | October',
 'June | July | August | September | October | November | December | January',
                                                              'March | April',
                         'April | June | July | August | September | October',
                                     'May | June | July | August | September',
                                                         'October | November',
                                               'August | September | October',
                                      'December | January | February | March',
                                                                    'October',
                                            'June | July | August | December',
                                                                'June | July',
                                  'September | October | November | December',
                                   'November | December | January | February']
Length: 27, dtype: str

========================================
good_months (25 unique values):
<ArrowStringArray>
[                    'May | September',                  'April | May | June',
                         'April | May',                 'November | December',
                  'December | January',                                    '',
                 'March | June | July',                     'September | May',
                   'September | April',                        'May | August',
                                 'All',                      'May | November',
                                 'May',                       'May | October',
              'June | July | December',                    'March | November',
                     'April | October',                     'July | November',
                    'November | April', 'January | February | March | August',
               'April | May | October',         'January | February | August',
                     'March | October',    'April | May | October | November',
                     'June | November']
Length: 25, dtype: str

========================================
avoid_months (14 unique values):
<ArrowStringArray>
[                      'January | February | March',
 'November | December | January | February | March',
                                                 '',
                              'March | April | May',
                               'January | February',
                             'June | July | August',
                        'January | February | July',
                       'May | June | July | August',
               'January | February | March | April',
                                'May | June | July',
                    'December | January | February',
                                      'June | July',
         'November | December | January | February',
            'December | January | February | March']
Length: 14, dtype: str

In [23]:
places.head()

,state,state_code,destination,tourism_type,best_months,good_months,avoid_months,why_best,international_draw,weather,crowd_level,description,category
0,Maranhão,MA,Lençóis Maranhenses,Nature / Ecotourism,June | July | August,May | September,January | February | March,Rainy season ends but lagoons still full — ide...,High,hot,moderate,Vast desert landscape of white sand dunes fill...,nature
1,Mato Grosso do Sul,MS,Pantanal,Wildlife / Ecotourism,July | August | September | October,April | May | June,November | December | January | February | March,Dry season — water levels low so wildlife conc...,Very High,hot,low,The world's largest tropical wetland — a UNESC...,nature
2,Amazonas,AM,Amazon Rainforest (dry season),Nature / Ecotourism,June | July | August | September,April | May,,The world's largest rainforest. Dry season off...,Very High,hot,low,"The world's largest rainforest, covering 60% o...",nature
3,Amazonas,AM,Amazon Rainforest (wet season),Nature / Ecotourism,January | February | March,November | December,,Wet season — easier navigation by boat. Flora ...,High,hot,low,Flooded forest season — boats navigate between...,nature
4,Pernambuco,PE,Fernando de Noronha (diving),Marine / Diving,August | September | October | November,December | January,March | April | May,Clearest waters for diving (up to 50m visibili...,Very High,warm,moderate,Brazil's most exclusive island destination — a...,beach

# 04. Exporting data ready for use in app

In [22]:
places.to_pickle('../01. Data/02. Processed Data/intelligence_ready.pkl')
places.to_csv('../01. Data/02. Processed Data/intelligence_ready.csv', index=False)